<ul>
	<li>
		<a href="#" onclick = "refreshTab('enquiryHome', '<?=$this->url(array('enquiryType' => 'home','action' => 'home'))?>'); return refreshTab('vypisDole', '<?=$this->url(array('enquiryType' => 'home','action' => 'list'))?>');">
		Anketa na hlavní stránce
		</a>
	</li>
	<!--
	<li>
		<a href="#" onclick = "refreshTab('enquiryHome', '<?=$this->url(array('enquiryType' => 'intranet','action' => 'home'))?>'); return refreshTab('vypisDole', '<?=$this->url(array('enquiryType' => 'intranet','action' => 'list'))?>');">
		Anketa v intranetu
		</a>
	</li>
	
	<li>
		<a href="#" onclick = "refreshTab('enquiryHome', '<?=$this->url(array('enquiryType' => 'webuser','action' => 'home'))?>');return refreshTab('vypisDole', '<?=$this->url(array('enquiryType' => 'webuser','action' => 'list'))?>');">
		Anketa pro registrované uživatele
		</a>
	</li>
	-->
</ul>