	<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
	    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
	        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabs-1">Jazykové mutace</a></li> 
	    </ul>
	    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
	    	<?=$this->page;?>    
					</div>  
				</div>   
                <script type="text/javascript">
    $(function() {
        $( "#tabsright" ).tabs();  
    });  

    var currentNo = 0;
	function newPhrase(){  
		$( "#r" + currentNo ).css('display',''); 
		currentNo++; 
	}  
    </script> 