<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<? if ($this->popup):$s = 'style="background:none"';endif; ?>
<? if ($_COOKIE['wfont']):$cla = 'class="wfont"';endif ?>
<html <?= $s ?> <?= $cla ?> xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="Language" content="czech"/>
    <meta name="Distribution" content="global"/>
    <meta name="Robots" content="INDEX,FOLLOW"/>
    <meta name="Expires" content="never"/>
    <meta name="Revisit-after" content="7 Days"/>
    <meta name="Resource-type" content="document"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="keywords" content="<?= $this->pageKw ?>"/>
    <meta name="description" content="<?= $this->pageDescription ?>"/>
    <meta name="google-site-verification" content="<?= $this->settings->getSettingValue('verifyCode') ?>"/>
    <title><?= ($this->isHomepage ? $this->pageTitleRaw : $this->pageTitle) ?></title>

        <!-- Plne CSS:       
   Nacitame asynchronne pomoci Enhance.js 
  -->        
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<?php if ( isset($_COOKIE['full-css']) ) : ?>
  		<link rel="stylesheet" href="/styles/style.min_zal.css">
<? else: ?>         
   	         <!-- Plne CSS:                      
   Nacitame asynchronne pomoci Enhance.js
  -->       
     <meta name="fullcss" content="/styles/style.min_zal.css">  
        <style>
            <?include("styles/critical.css");?>         
        </style>      
        <script>   
            document.cookie = 'full-css=1; expires=' + (new Date(new Date().getTime() + 86400000)).toGMTString() + '; path=/'
        </script>
        <noscript> 
             <link rel="stylesheet" href="/styles/style.min_zal.css">
        </noscript>
    <? endif ?>    
    <? if ($this->node->nodeId == 4410): ?>
        <link rel="stylesheet" href="/styles/basket.css" type="text/css" media="screen"/>
    <? endif ?>   


    <!--[if lt IE 9]>
    <script type='text/javascript' src="/js/reponsiveIE8/html5.js"></script>
    <script type='text/javascript' src="/js/bootstrap/js/respond.js"></script>
    <![endif]-->


    <? $ga = $this->settings->getSettingValue('googleCode');
    $mOrders = new module_Eshop_Orders(); ?>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', '<?=$ga?>', 'auto');
        ga('require', 'displayfeatures');
        <?=$this->mGooleDim->getGetGooleDimension($this->node, $this->mEshop->basket, $this->mEshop->basket->getSum($this), $this);?>
        <?=$this->mGooleDim->getIP();?>
        <?if($this->inputGet->done):?>
        <?=$_SESSION['ecommerce'];?>
        <?//die;
        endif;?>
        <?=$mOrders->renderReverseOrders();?>
    </script>
    <link rel="Shortcut icon" href="/images/favicon.ico" type="image/x-icon"/><? if (!is_numeric(strpos($this->url, 'nakupni-kosik'))): ?>
    <script type="text/javascript">
        //<![CDATA[
        var _hwq = _hwq || [];
        _hwq.push(['setKey', '6F59C8EA4B805078B516648CCBE1991C']);
        _hwq.push(['setTopPos', '60']);
        _hwq.push(['showWidget', '21']);
        (function () {
            var ho = document.createElement('script');
            ho.type = 'text/javascript';
            ho.async = true;
            ho.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.heureka.cz/direct/i/gjs.php?n=wdgt&sak=6F59C8EA4B805078B516648CCBE1991C';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ho, s);
        })();
        //]]>
    </script><? endif ?>
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window,
            document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1057700440983298');
        fbq('track', "PageView");
        <?=$this->mFacebookPixel->getFacebookTrack($this->node, $this->mEshop->basket, $this->mEshop->basket->getSum($this), $this);?>
    </script>
    <!-- End Facebook Pixel Code -->
    <? if ($_COOKIE['wfont']): ?>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700' rel='stylesheet'
          type='text/css'>
    <? else: ?>
        <script>
            WebFontConfig = {
                google: {families: ['Roboto+Condensed:400,700']},
                active: function () {
                    document.cookie = 'wfont=1; expires=' + (new Date(new Date().getTime() + 86400000)).toGMTString() + '; path=/'
                }
            };
        </script>
        <script src="//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js" async defer></script>
    <link rel="prefetch"
          href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700"><? endif ?>
   
</head>    
<body>
<div class="container">
    <div id="main">
        <?= $this->render('parts/header.phtml'); ?>
        <?= $this->render($this->container); ?>
    </div>
    <?= $this->render('parts/footer.phtml'); ?>
    <script type="text/javascript">
        var seznam_retargeting_id = 26189;
    </script>
    <script type="text/javascript" src="/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="//c.imedia.cz/js/retargeting.js"></script>
    <script type="text/javascript" src="/js/start.js"></script>
    <script type="text/javascript" src="/js/jquery.autocomplete.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.js"></script>
    <script type="text/javascript" src="/js/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/gallery/jssor.core.js"></script>
    <script type="text/javascript" src="/js/gallery/jssor.utils.js"></script>
    <script type="text/javascript" src="/js/gallery/jssor.slider.js"></script>
    <? if ($this->node->nodeId == 4410): ?>
        <script type="text/javascript" src="/js/basket.js">></script>
    <? endif ?>
    <? if ($this->showHPBan): ?>
        <script type="text/javascript" src="/js/hp_fuctions.js" defer async></script>
    <? endif; ?><? if ($this->isgallery && !$this->isHomepage): ?>
        <script type="text/javascript">
            $(".openGallery").click(function (event) {
                event.preventDefault();
                $('#photoGalleryPop').lightbox_me({
                    centered: true,
                    closeSelector: "#closeGallery"
                });
                var index = $(this).attr("data-counter");
                slider.$GoTo(index);
            });
        </script>
        <script src="/js/jquery.lightbox_me.js"></script>
        <script src="/js/gallery.functions.js"></script><? endif; ?>
    <script src="/js/jquery.magnific-popup.js"></script>
  
      <script src="/js/enhance.js" defer async></script>
      <script src="/js/respond.min.js" defer async></script>    
      <script src="/js/picturefill.min.js" defer async></script>
        <script type="text/javascript" defer async>  
        var _smartsupp = _smartsupp || {};
        _smartsupp.key = "50a1f511dd87a530fcdf91d1b9ba2ec426d93f71";
        _smartsupp.gaKey = '<?=$ga?>';
        window.smartsupp || (function (d) { 
            var s, c, o = smartsupp = function () {
                o._.push(arguments)
            }; 
            o._ = []; 
            s = d.getElementsByTagName('script')[0];
            c = d.createElement('script');
            c.type = 'text/javascript';
            c.charset = 'utf-8';  
            c.async = true;
            c.src = '//www.smartsuppchat.com/loader.js';
            s.parentNode.insertBefore(c, s);
        })(document);  
    </script>
    			<script>  
		$("#show-gdpr" ).click(function() {
			$( "#cookies-gdpr" ).toggle();    
  		});
  		  		$.ajax({   
   url: '?banner=1',
   success: function(data) {
      $("#banner-ajax").append(data);       
        
   }  
});  
</script>     
</body>
</html>