<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<?if($this->popup):
	$s = 'style="background:none"';
endif;?>
<html <?=$s?> xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="Language" content="czech" />
        <meta name="Distribution" content="global" />
        <meta name="Robots" content="INDEX,FOLLOW" />
        <meta name="Expires" content="never" />
        <meta name="Revisit-after" content="7 Days" />
        <meta name="Resource-type" content="document" />
          <meta name="author" content="eportaly.cz" />
		<meta name="keywords" content="<?=$this->pageKw?>" />  
		<meta name="description" content="<?=$this->pageDescription?>" />
		<meta name="google-site-verification" content="<?=$this->settings->getSettingValue('verifyCode')?>" />
		
		<meta name="google-site-verification" content="dE7dO2D4UbMxSaDZCxvlp1XOP7B_BlY1-AjPWlFG0Ew" />
		<!--<link rel="shortcut icon" href="/images/schueller_favicon.ico">-->
		<?$this->pageTitleRaw= str_replace('NIVONA', 'JURA', $this->pageTitleRaw);?>
		<?$ua = strtolower($_SERVER['HTTP_USER_AGENT']);?>
		<title><?=($this->isHomepage?$this->pageTitleRaw:$this->pageTitle)?></title> 
		<?if(stripos($ua,'android') !== false || $_GET['fuck']):?>
			<link rel="stylesheet" href="/styles/screen1NewAAAAAA.css" type="text/css" media="screen"/>
		<?else:?> 
       		<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
       		<link rel="stylesheet" href="/styles/screen1NeA.css" type="text/css" media="screen"/>
       	<?endif;?>    
       	<link rel="stylesheet" href="/styles/jquery-ui.css" type="text/css" media="screen">
		<script type="text/javascript" src="/js/jquery-1.11.1.min.js"></script>  
  		<script type="text/javascript" src="/js/fb1.js"></script>  
	 	<?$ga = $this->settings->getSettingValue('googleCode');?>
	 	<!-- Start of Smartsupp Live Chat script -->
<script type="text/javascript">
var _smartsupp = _smartsupp || {};
_smartsupp.key = "50a1f511dd87a530fcdf91d1b9ba2ec426d93f71";
_smartsupp.gaKey = '<?=$ga?>'; 
window.smartsupp||(function(d) {
	var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
	s=d.getElementsByTagName('script')[0];c=d.createElement('script');
	c.type='text/javascript';c.charset='utf-8';c.async=true;
	c.src='//www.smartsuppchat.com/loader.js';s.parentNode.insertBefore(c,s);
})(document);
</script>
<!-- End of Smartsupp Live Chat script -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?=$ga?>', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
  <?if($this->inputGet->done):?>
    <?=$_SESSION['ecommerce'];?> 
	  <?//die;
	  endif;?>
	  

</script>
		<link rel="Shortcut icon" href="/images/favicon-kava.ico" type="image/x-icon" />
	<script type="text/javascript">
//<![CDATA[
var _hwq = _hwq || [];
    _hwq.push(['setKey', '6F59C8EA4B805078B516648CCBE1991C']);_hwq.push(['setTopPos', '60']);_hwq.push(['showWidget', '21']);(function() {
    var ho = document.createElement('script'); ho.type = 'text/javascript'; ho.async = true;
    ho.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.heureka.cz/direct/i/gjs.php?n=wdgt&sak=6F59C8EA4B805078B516648CCBE1991C';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ho, s);
})();
//]]>
</script> 
	</head> 
	
	<?if($this->popup):?>
	<body style="background:none">
		<?$this->disableLeft = true?>
		<?=$this->render('popup.phtml'); ?>	
	</body>
	<?else:?>	
	<?if($this->disableLeft):
	   	$back = 'style="background: url(../images/bck-1b.png) top center repeat-y;"';
	   endif;?>
	<body <?=$back?>>     
		
		<div id="container">
    		<div id="main" > 
				<?=$this->render($this->container); ?>	
			</div>      
			<?=$this->render('parts/header.phtml'); ?> 
			<?=$this->render('parts/footer.phtml'); ?> 

			 		<div id="rightBan">
			 				<div id="rightBanFix">
			 			<img src="/images/bann-doprava.png" alt="Doprava zdarma pro objednávky nad 5 tisic Kč.">
			 			<img src="/images/bann-spec.png" alt="Autorizovaný prodejce"> 
			 			<img src="/images/bann-overeno.png" alt="Oveřeno zákazníky"> 
			 			<img src="/images/bann-tel.png" alt="Odborné poradenství <?=$this->phoneNum?>">
      	 	<!--<a rel="nofollow" target="_blank" href="http://www.vipelektro.cz/e-shop/kavovar-catler-es-8012#?utm_source=nivona&amp;utm_medium=banner&amp;utm_campaign=pravy&amp;utm_content=catler">
      	 	</img></a> -->
     			 </div>     
       </div>  
				 
				  
		<?endif;?>
		<script type="text/javascript">
/* <![CDATA[ */
var seznam_retargeting_id = 26189;
/* ]]> */
</script>
<script type="text/javascript" src="//c.imedia.cz/js/retargeting.js"></script>
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//script.crazyegg.com/pages/scripts/0041/2713.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script> 

<script type="text/javascript" src="/js/start.js"></script> 
	<script type="text/javascript" src="/js/jquery.autocomplete.js"></script> 
	  		<script type="text/javascript" src="/js/jquery-ui.js"></script> 
		 <script type="text/javascript" src="/js/gallery/jssor.core.js"></script> 
    	<script type="text/javascript" src="/js/gallery/jssor.utils.js"></script>
    	<script type="text/javascript" src="/js/gallery/jssor.slider.js"></script>
   	    	  
 <?if($this->showHPBan):?>
		<script type="text/javascript" src="/js/hp_fuctions.js"></script>
	<?endif; ?>
		
	<?if($this->isgallery && !$this->isHomepage):?>
		<script type="text/javascript">
				$(".openGallery").click(function(event) {
					event.preventDefault();
					$('#photoGalleryPop').lightbox_me({
						centered : true,
						closeSelector : "#closeGallery"
					});
					var index = $(this).attr("data-counter");
					slider.$GoTo(index);
				});
		</script>  
 		<script src="/js/jquery.lightbox_me.js"></script>
    	<script src="/js/gallery.functions.js"></script>
	<?endif; ?>
</body>
</html>