	
	
		<div class="spacer10">&nbsp;</div>
		<div class="spacer10">&nbsp;</div>
		<div class="spacer10">&nbsp;</div>
	<div id="err_<?=$this->tableParentTab?>"></div>
	 
	<?= $this->render('/controls/admin/forms/UserList.phtml');?>
	<div style="position:absolute; top:7px; left:-2px; padding:0px 0px 0px 20px; width:880px;">
	<?php echo $this->formSubmit('termine' . $this->randIdentifier, 'Zpět na e-mail', array('class'=>'fsubmit', 'style'=>'float:right', "onclick" => "getModalWindow(2).hide()", 'iconClass' => "noteIcon")) ?>		
					
	<?= $this->formSubmit('chooseSelected' . $this->randIdentifier, 'Přidat osoby mezi příjemce', array('class'=>'fsubmit', "onclick" => "return submitFormAjax('form" . $this->randIdentifier . "', '".$this->url(array('controller' => 'mailing','action' => 'setRecipients', 'calledFrom' => $this->calledFrom))."', '$this->tableParentTab', 'setMailRecipients', '', true );")) ?>		
	<?= $this->formSubmit('chooseAll' . $this->randIdentifier, 'Odeslat email všem', array('class'=>'fsubmit', "onclick" => "return submitFormAjax('form" . $this->randIdentifier . "', '".$this->url(array('controller' => 'mailing','action' => 'setRecipientsGrouped', 'calledFrom' => $this->calledFrom))."', '$this->tableParentTab', 'setMailRecipients', '', true );")) ?>		
	</div> 