<div id="err_newMailForm"></div>
<form id="newMailForm" action="<?= $this->url(array('controller' => 'mailing','action' => 'send')) ?>" method="get">		
	<table class="modalTable">
		<tr>
			<td class="tkey">
				Odesílatel
			</td>
			<td>
				<?php echo $this->formComboBox('mailSender',$this->input->sender, array('class'=>'ftext', 'style'=>''), $this->possibleSenders) ?>			 
				<a class="helpico" style="margin-right:10px;" href="#" title="Pokud zadáváte ručně napište přímo email nebo celý tvar  Jméno (jmeno@domena.cz)">&nbsp;</a>
			</td>			
		</tr>
		<tr>
			<td>
				<?php echo $this->formSubmit('setRecipientsB', 'Příjemci pošty', array('class'=>'fsubmit', "onclick" => "return showModal('Výběr příjemců','". $this->url(array('controller' => 'mailing','action' => 'showRecipientsForm')) ."', 2);")) ?> <span id="recipientsCount"> </span>								
			</td>
			<td>								
				<a class="helpico fl_right" href="#" title="Zde můžete vybrat příjemce, nebo je zadat ručně, oddělené čárkou nebo středníkem" style="float:right;">&nbsp;</a>	
				<?php echo $this->formTextarea('recipients',$this->input->recipients, array('class'=>'ftext', 'rows' => 2, 'style'=>'width:90%; scroll:auto;')) ?>						
			</td>			
		</tr>
		<tr>
			<td>
				Předmět
			</td>
			<td>
				<?php echo $this->formText('mailHead',$this->input->head, array('class'=>'ftext', 'style'=>'width:90%;')) ?>			
			</td>			
		</tr>
		<tr>
			<td colspan="2">
			<?php echo $this->formWysiwyg('mailContent',$this->input->text, 400, 'fck_', array('toolbar' => 'CMSToolbar')); //EmailToolbar ?>
			</td>
		</tr>    
		<tr>
			<td colspan="2">
			<?php echo $this->formSubmit('sendMail', 'Odeslat', array('class'=>'fsubmit', "onclick" => "setWysiwygContent('fck_mailContent'); return submitFormAjax('newMailForm', '".$this->url(array('controller' => 'mailing','action' => 'send'))."', 'vypisDole', 'tab-submit-close', '', true );", 'iconClass' => "noteIcon")) ?>		
			<?php echo $this->formSubmit('saveMailB', 'Uložit jako koncept', array('class'=>'fsubmit', "onclick" => "setWysiwygContent('fck_mailContent'); return submitFormAjax('newMailForm', '".$this->url(array('controller' => 'mailing','action' => 'save'))."', 'vypisDole', 'tab-submit', '', true );", 'iconClass' => "noteIcon")) ?>						
			
			</td>
		</tr>
	</table>
</form>