	<?$disableProperty = array('dph','ordersEmailName','ordersEmail');?>
	<form action="<?=$this->url(array('controller' => 'settings','action' => 'save'))?>" method="post" id="settingsForm">	  
	<table class="normal">	 
		<? foreach ($this->settings as $groupName => $group): ?>    
		<tr>
			<td class="formcell tbold" colspan="2"><?=$this->s_Translate_groups[$groupName]?></td>
		</tr>	
		<? foreach ($group as $setting):
		if(in_array($setting['variable'], $disableProperty)){
			continue;
		}
			
		if($setting['onlySuperadmin'] == 1 && !$this->isSuperAdmin){ 
			continue;
		}  
		
		if($setting['displayInLeftMenu'] == 1){  
			continue;
		} 
		
		
		?>
		<tr>
			<td class="formcell"><?=$this->s_Translate[$setting['variable']] ?></td>			
			<td class="formcell">
				<?php 
				switch ($setting['formType']){
					default:
					case 'Text':
						echo $this->{'form'.$setting['formType']}($setting['variable'], $setting['value'], array('class' => 'ftext'));
						break;
						
					case 'Select':						
						
						$options = array();
						$o = explode(';', $setting['options']);
						foreach ($o as $opt){
							list($k, $v) = explode('=', $opt);
							$options[$k] = $v;
						}
												
						echo $this->{'form'.$setting['formType']}($setting['variable'], $setting['value'], array('class' => 'ftext', 'value'=>$setting['value']), $options );
				}
				 ?>
			</td>						
		</tr>
		<? endforeach;?>	
		<? endforeach;?>	
		<tr>	
			<td class="formcell" colspan="2">		
				<?php echo $this->formSubmit('saveSetB', 'Uložit', array('class'=>'fsubmit fsBig')) ?>	
				<a onclick="window.history.back(); return false;" id="cancelLink" title="Změny nebudou uloženy">Zrušit</a>										
			</td>
		</tr> 
		
	</table>	 
	</form>