<?
	switch ($this->curentAction){
		default:
		case 'index';
			?> 
				<div id="tabsright"> 
				    <ul>
				        <li><a href="#tabs-1">Statistiky</a></li> 
				    </ul>
				    <div id="tabs-1"> 
				    	<iframe frameborder="0" name="mainright" id="mainright" src="/statsframe" style="width:100%; height:100%;  margin:0px -20px -20px -10px; border:none;" />  
					</div> 
				</div>
                <script type="text/javascript">  
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });
			    </script> 
			<? 
			break;
		case 'detail';
			?>
			<?=$this->pageContent;?>   
			<?
			break; 
	}