<ul class="leftWidgetMenu">
	<li>
		<a href="#" onclick = "return refreshTab('statsHome', '<?=$this->url(array('action' => 'userAudit'))?>');">
		Historie uživatelských akcí
		</a>
	</li>
	<li>
		<a href="#" onclick = "return refreshTab('statsHome', '<?=$this->url(array('action' => 'fileAudit'))?>');">
		Statistiky stažení souborů
		</a>
	</li>
	<li>
		<a href="#" onclick = "return refreshTab('statsHome', '<?=$this->url(array('action' => 'contentsAudit'))?>');">
		Statistiky publikování obsahu 
		</a>
	</li>
</ul>