<ul  class="leftCmsMenu">
    <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#visitors" target="mainright">Souhrn</a> </li>
    <li> <strong>Kdy:</strong>
        <ul>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#month" target="mainright">Za měsíc</a> </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#daysofmonth" target="mainright">Dny v měsíci</a> </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#daysofweek" target="mainright">Dny v týdnu</a> </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#hours" target="mainright">Hodiny</a> </li>
        </ul>
    </li>
    <li> <strong>Kdo:</strong>
        <ul>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#countries" target="mainright">Země</a> 
            	<ul>
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=alldomains" target="mainright">Úplný seznam</a> </li>
            	</ul>
            </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#visitors" target="mainright">Hosté</a> 
            	<ul>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=allhosts" target="mainright">Úplný seznam</a> </li>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=lasthosts" target="mainright">Poslední návštěva</a> </li>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=unknownip" target="mainright">Nepřeložená IP adresa</a> </li>
	            </ul>
            </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#robots" target="mainright">Roboti</a> 
            	<ul>
	            	<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=allrobots" target="mainright">Úplný seznam</a> </li>
	            	<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=lastrobots" target="mainright">Poslední návštěva</a> </li>
	            </ul>
            </li>
        </ul>
    </li>
    <li> <strong>Navigace:</strong>  
        <ul>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#sessions" target="mainright">Trvání návštěv</a> </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#filetypes" target="mainright">Typ souboru</a> </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#urls" target="mainright">Zobrazeno</a> 
	            <ul>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=urldetail" target="mainright">Úplný seznam</a> </li>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=urlentry" target="mainright">Vstupní stránky</a> </li>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=urlexit" target="mainright">Výstupní stránky</a> </li>
	            </ul>
            </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#os" target="mainright">OS</a> 
            	<ul>
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=osdetail" target="mainright">Verze</a> </li>
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=unknownos" target="mainright">Neznámý</a> </li>
            	</ul>
            </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#browsers" target="mainright">Browsery (prohlížeče)</a>
            	<ul>
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=browserdetail" target="mainright">Verze</a> </li>
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=unknownbrowser" target="mainright">Neznámý</a> </li>
            	</ul>
            </li>
        </ul>
    </li>
    <li> <strong>Reference:</strong>
        <ul>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#referer" target="mainright">Původ</a> 
            	<ul>
	            	<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=refererse" target="mainright">Odkazující vyhledávače</a> </li>
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=refererpages" target="mainright">Odkazující stránky</a> </li>
            	</ul>
            </li>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#keys" target="mainright">Hledání</a>
            	<ul>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=keyphrases" target="mainright">Hledaná slovní spojení</a> </li>
		            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=keywords" target="mainright">Hledané výrazy</a> </li>
		        </ul>
            </li>
        </ul>
    </li>
    <li> <strong>Ostatní:</strong>
        <ul>
            <li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#misc" target="mainright">Různé</a>
            	<ul>
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright#errors" target="mainright">Chybové kódy HTTP</a> 
            		<li> <a onclick="return checkIframe(this.href)" href="/statsframe?framename=mainright&amp;output=errors404" target="mainright">Nenalezené stránky</a> </li>
            	</ul>
            </li>
        </ul>
    </li>
</ul>