<form id="PageForm" class="validate" name="PageForm" method="post"  enctype="multipart/form-data">

<?php 
if(!$this->isEdit){   
	echo $this->formHidden('parentId',$this->curentNode);
}
	echo $this->formHidden('contentId',$this->contentId);    
?>
	
<div id="tabsDetail" class="ui-tabs ui-widget ui-widget-content ui-corner-all"> 
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all"> 
        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabsd-1">Vlastnosti</a></li> 
        <?if(!$this->inFileBranch):?>
        <li class="ui-state-default ui-corner-top"><a href="#tabsd-2">Optimalizace pro vyhledávače</a></li> 
        <li class="ui-state-default ui-corner-top"><a href="#tabsd-3">Nastavení</a></li>   
	        <?if($this->languages->isMultiLanguage):?>
	        <li><a href="#tabsd-4">Jazykové verze</a></li> 
	        <? endif; ?>  
        <? endif; ?>
        
        <?if($this->advertsPositions):?>
        <li class="ui-state-default ui-corner-top"><a href="#tabsd-5">Reklamní pozice</a></li> 
        <? endif; ?>
        <?if($this->isEdit):?>
        <li class="ui-state-default ui-corner-top"><a href="#tabsd-6">Historie stránky</a></li> 
        <? endif; ?> 
        <?if($this->loadsrovnavace):?>
        <li class="ui-state-default ui-corner-top" id="tabsrovnace"><a href="#tabsd-7">Cenové srovnávače</a></li>
        <?endif?> 
        
    </ul>
    <div id="tabsd-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom">  
    	<?=$this->contentForm;?>
    </div>
    <?if(!$this->inFileBranch):?> 
    <div id="tabsd-2" class="ui-tabs-panel ui-widget-content ui-corner-bottom">  
    	<?=$this->contentSEO;?>
    </div>
    <div id="tabsd-3" class="ui-tabs-panel ui-widget-content ui-corner-bottom">  
    	<?=$this->contentSettings;?>
    </div>
	    <?if($this->languages->isMultiLanguage):?>
	    <div id="tabsd-4" class="ui-tabs-panel ui-widget-content ui-corner-bottom">  
	    	<?=$this->contentLanguages;?>
	    </div>
	    <? endif;?>    
    <? endif;?>
    <?if($this->advertsPositions):?>
    <div id="tabsd-5" class="ui-tabs-panel ui-widget-content ui-corner-bottom">  
    	<?=$this->contentAdverts;?>
    </div>
    <? endif; ?>
    <?if($this->isEdit):?>
    <div id="tabsd-6" class="ui-tabs-panel ui-widget-content ui-corner-bottom">  
    	<?=$this->contentHistory;?>
    </div>
    <? endif; ?>  
    <?if($this->loadsrovnavace):?>
    <div id="tabsd-7" class="ui-tabs-panel ui-widget-content ui-corner-bottom"> 
    	<div class="loading-img"><img src="/admin/images/icons/loading.gif" /></div> 
    </div>
   <? endif; ?>
</div> 
<?=$this->render('controls/admin/forms/_Save.phtml'); ?>  
</form>
<script type="text/javascript">
    $(function() {
        $( "#tabsDetail" ).tabs();
    }); 
    </script>
     <script>
    $(window).load(function(){  


    });
    $( "#tabsrovnace" ).click(function() {
    	if($('.loading-img').css('display') == 'block'){
    		$.ajax({
    			url: "<?=$this->url(array('module' => 'cms', 'controller' => 'structure', 'action' => 'rendersrovnace','node'=> $this->node->nodeId))?>",
      			success: function(data) {
      				$('.loading-img').css('display', 'none');
      				$('#tabsd-7').html(data);
      			},
      			type: 'POST'
    		});
    	}
    	});
        </script>