<?$items = $this->mEshop->basket->getItems();
if($items):?>
          <div id="left-column" class="fLeft">  
		  <? if(isset($this->voucher)):
		  $voucherErr = false;
		  $voucherInfo = "Kupón byl úspěšně vložen";
			if($this->voucher === 0){
				$voucherInfo = 'Zadaný kód "'.$this->input->kod.'" je neplatný.';
				$voucherErr = true;
				unset($this->voucher);
				}	
			if($this->voucher['status'] == 2){
				$voucherInfo = "Kupón \"".$this->input->kod."\" již byl použit!";
				$voucherErr = true;
				unset($this->voucher);
				}
			if($this->voucher['status'] == 3){
				$date = new DateTime($this->voucher['valid']);
				$voucherInfo = 'Je nám líto, ale kupón "'.$this->input->kod.'" byl platný pouze do: '. $date->format('j.n.Y').'.';
				$voucherErr = true;
				unset($this->voucher);
				}
			if($this->voucher['status'] == -1){
				$voucherInfo = "Kupón \"".$this->input->kod."\" se nevztahuje na žádné zboží v košíku!";
				$voucherErr = true;
				unset($this->voucher);
				}
			$voucherClass = $voucherErr?'vErr':'vInfo';
		  ?>
		  <div id="voucherinfo" class="<?=$voucherClass?>">
			<?=$voucherInfo?>
		  </div>
		  <?endif;?>
          	 <?=$this->render('templates/Eshop/ItemsList.phtml'); ?>
          	 <div class="spacer10"></div>
          	 <?=$this->render('templates/Eshop/deliveryBlock.phtml'); ?>
            <div class="clear"></div>  
          </div>     
          <?=$this->render('templates/Eshop/priceBlock.phtml'); ?>
       <div class="spacer20"></div> 
          <div class="fRight marRight10">  
          	<div class="fLeft marRight10">
          		<a  class="butt fLeft" href="javascript:history.back()"><span class="red fBold butt i-block fs16 bgrNoRep">Zpět</span></a>  
     		</div>
     		
     		<div class="fLeft">
           	 	<button type="submit" class="butt fRight" name="step[2]"><span class="red fBold butt i-block fs16 bgrNoRep">Další krok</span></button>
           	 </div>
          </div>
<?else:?> 
<div class="spacer10"> </div>   
	<div class="spacer10"> </div>  
	<div class="spacer10"> </div>   
	<div class="tcenter">
	<p>Nemáte v košíku žádné zboží.</p>
	</div> 
 <?endif;?>