                <div class="spacer10">&nbsp;</div>
                <h2 class="mini">Jiné možnosti</h2>
                <p>Chcete si doobjednat zboží? <a href="javascript:history.back();">Pokračujte v nákupu</a>, stav zboží ve vašem košíku zůstává zachován.<br />
                <!--
                Přejete-li se seznámit se s podmínkami nákupu, přečtěte si článek 
                <a href="<?=Utils::getWebPath($this->tree->getNodeById($this->config->instance->podminkyNodeId)->path)?>">Jak nakupovat - obchodní podmínky</a></p>
                -->  