<div class="clear">&nbsp;</div>    
<div class="container-our-eshop basket-pos">      
    <h3><a href="/jura/nase-e-shopy">Naše další E-shopy</a></h3>        
		<div class="item-eshop" id="jura">        
			<a href="https://www.svycarskekavovary.cz/jura" class="item-eshop-link">
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo jura"></span>
					<span class="item-eshop-text">Autorizovaný prodejce JURA</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/jura-e8-front-min.jpg">
				</span>
				<p><strong>www.svycarskekavovary.cz/jura</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="nivona">   
			<a href="https://www.nivona-eshop.cz" class="item-eshop-link">
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo nivona"></span>
					<span class="item-eshop-text">Specializovaný eshop NIVONA</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/841.jpg">
				</span>
				<p><strong>www.nivona-eshop.cz</strong></p>	
			</a>  
		</div>
		<div class="item-eshop" id="liebher">   
			<a href="https://www.topchlazeni.cz" class="item-eshop-link">
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo lie"></span>
					<span class="item-eshop-text">Chlazení LIEBHERR - Eshop</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/gnp2855-20_sod.jpg">
				</span>
				<p><strong>www.topchlazeni.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="chlad">   
			<a href="https://www.chladnickanavino.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo chlad"></span>
					<span class="item-eshop-text">Speciálka na domácí vinotéky</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/dunavox-dx-30.80.jpg">
				</span>
				<p><strong>www.chladnickanavino.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="faber">   
			<a href="https://www.faber-eshop.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo faber"></span>
					<span class="item-eshop-text">Italské digestoře FABER</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/FABER_Stilo_SP_SRM_X_A90-1488.jpg">
				</span>
				<p><strong>www.faber-eshop.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="airforce">   
			<a href="https://www.airforce-eshop.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo airfor"></span>  
					<span class="item-eshop-text">Luxusní odsavače Airforce</span>
				</span>  
				<span class="item-eshop-link-content-h">     
					<img src="/images/footer/f181tlc45bkx1362.jpg">
				</span>
				<p><strong>www.airforce-eshop.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="elica">   
			<a href="https://www.italskedigestore.cz/elica" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo ital"></span>
					<span class="item-eshop-text">Autorizovaný eshop Elica</span>  
				</span>  
				<span class="item-eshop-link-content-h">          
					<img src="/images/footer/3310-1312488952.jpg">
				</span>
				<p><strong>www.italskedigestore.cz/elica</strong></p>	
			</a>  
		</div>        
		<div class="item-eshop" id="lord">        
			<a href="https://www.vipelektro.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo vip"></span>   
					<span class="item-eshop-text">Německé spotřebiče LORD</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/586840.jpg">
				</span>
				<p><strong>www.vipelektro.cz</strong></p>	
			</a>  
		</div>        
			<div class="item-eshop" id="laura">        
			<a href="https://www.parnizehleni.cz/laurastar" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo laura"></span>   
					<span class="item-eshop-text">Švýcarské žehlící systémy</span>
				</span>      
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/laurastar-prod.jpg">
				</span>
				<p><strong>www.parnizehleni.cz/laurastar</strong></p>	      
			</a>    
		</div>         
	</div>