<?if(!$_COOKIE['eu-cookises']):?>
		<div id="cookies"> 
			<div id="cookies-inner">
				<p>S cílem usnadnit uživatelům používat naše webové stránky využíváme cookies. Používáním našich stránek souhlasíte s ukládáním souborů <a href="/jura/cookies">cookie</a> na vašem počítači / zařízení.</p> 
				<p class="pull-left">
					<a href="/jura/zpracovani-osobnich-udaju" 
					rel="nofollow" id="cookie-info">Zpracování osobních údajů</a>.
				 <a href="#" id="setCooksiesa">Rozumím</a>
				</p>
			</div>  
			</div>
		<?endif?>       