<?php											

$mArticle = new module_Articles();
$articles = $mArticle->getTopArticles(5);


?>
<script src="/js/functions9.js" type="text/javascript">
<script src="/js/mootools-1.2.5-core.js" type="text/javascript">
<script src="/js/mootools-1.2.5.1-more.js" type="text/javascript">



 <div id="akc-nab">
<p>Naše akční nabídky STAVIS!</p>
   <?foreach ($articles  as $item):?>
          <div class="banner"><img src="<?=$item['photos']['path']?>" alt="<?=$item['photos']['name']?>">
          
            <div class="banner-popis">
            
         
              <p><span><?=$item['title'] ?></span><br>
                <br>
                <p><?= helper_FrontEnd::reduceText(strip_tags($item['html']),100)?></p> <br>
                <br>
                <a class="more fRight" href="<?= $item['path']?>">více zde</a> </p>
                <? endforeach; ?>
            </div>
          </div>
          <div class="clear">&nbsp;</div>
          <div id="nav-panel">
            <ul>
              <li><a class="selected" href="">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
            </ul>
          </div>

          <div class="clear">&nbsp;</div>
          <p><span>Chcete naše novinky a akční nabídky <a href="/novinky-na-email">dostávat na email</a>?</span></p>
        </div>
        <div id="corner"></div>
