<div id="footer">
	<div class="container">      
	<div class="fisrt-footer">
		<div class="content">
			<div class="column2-footer">    
				<div class="column first">   
					<div class="column2-insert">
						<div class="column-insert first">        
                        <span class="spant2">SVYCARSKEKAVOVARY.CZ</span>       
                  		        <p><a rel="nofollow" href="/jura/vse-o-nakupu">Vše o nákupu</a></p>
                  	        	<p><a rel="nofollow" href="/jura/obchodni-podminky">Obchodní podmínky</a></p>
                  		        <p><a rel="nofollow" href="/jura/zpracovani-osobnich-udaju">Zpracování osobních údajů</a></p>
                                  <p><a rel="nofollow" href="/jura/kontakty">Kontakty</a></p>  
                        </div>     
						<div class="column-insert second">   
						<span class="spant2">Proč nakupovat u nás</span>
						<?$this->dopravaNode = $this->tree->getNodeSimple(75076)?>     			      			
							<p>
								<a rel="nofollow" href="<?= $this->dopravaNode ->path?>"><?= $this->dopravaNode ->title?></a>
							</p>   
							<p>
								<a rel="nofollow" href="/jura/bezpecny-nakup">Bezpečný nákup</a>
							</p>
							<p> 
								<a rel="nofollow" href="/jura/bezpecny-nakup#zarakt">Záruka aktivní řešení reklamací</a>
							</p>
							<p>
								<a rel="nofollow" href="/jura/bezpecny-nakup#kom">Záruka aktivní komunikace</a>
							</p>
							<p>
								<a rel="nofollow" href="/jura/bezpecny-nakup#zarprod">Záruka původu produktů</a>
							</p>
							<p>   
								<a rel="nofollow" href="/jura/bezpecny-nakup#kval">Záruka kvality</a>
							</p>  
								<p>
								<a rel="nofollow" href="/jura/zpracovani-osobnich-udaju">Zpracování osobních údajů</a>
							</p>     
						</div>      
					</div>
				</div>              
				<div class="column second">  
                    <div class="logo-wrapper">      
                        <span class="spant2">NAŠE ESHOPY</span>     
                            <div class="logo-item"><a class="jura-min" href="/jura/nase-e-shopy#jura">
								<span class="top">    
									<p class="top-img">
										<img style="float: left; width: 60px; " src="/images/footer/jura-e8-front-min.jpg"> 
									</p>        
							 		<p class="top-text">Espresso kávovary JURA jsou luxusní švýcarské kávovary, které vynikají svou jednoduchostí a maximální funkčností.
										     
									 </p>         
								</span>
							</a></div>    
							<div class="logo-item"><a class="nivona-min" href="/jura/nase-e-shopy#nivona">
							<span class="top">
									<p class="top-img">  
										<img style="float: left; width: 60px; " src="/images/footer/841.jpg"> 
									</p>  
							 		<p class="top-text">Domácí automatické kávovary NIVONA patří k předním výrobcům automatických pressovačů, které s německou precizností zpracovávají švýcarskou technologii.
										   
									 </p>         
								</span>
								</a>
							</div>
							<div class="logo-item"><a class="liebher-min" href="/jura/nase-e-shopy#liebher">
							<span class="top">
									<p class="top-img">
										<img style="float: left; width: 60px; " src="/images/footer/gnp2855-20_sod.jpg"> 
									</p>  
							 		<p class="top-text">Certifikovaný prodejce této značky. Věříme, že si vyberete z našeho kompletního sortimentu.
										   
									 </p>         
								</span>
							</a></div>
							<div class="logo-item"><a class="chladni-min" href="/jura/nase-e-shopy#chlad">
							<span class="top">
									<p class="top-img">
										<img style="float: left; width: 60px; " src="/images/footer/dunavox-dx-30.80.jpg"> 
									</p>  
							 		<p class="top-text">Specializovaný maloobchod zabývající se výhradně prodejem chladniček na víno (domácích vinoték).
										   
									 </p>         
								</span>
							</a></div>
							<div class="logo-item"><a class="faber-min" href="/jura/nase-e-shopy#faber">
							<span class="top">
									<p class="top-img">
										<img style="float: left; width: 60px;" src="/images/footer/FABER_Stilo_SP_SRM_X_A90-1488.jpg"> 
									</p>  
							 		<p class="top-text">Jsme specializovaným prodejcem špičkových italských odsavačů par FABER
										   
									 </p>         
								</span>
							</a></div>
							<div class="logo-item"><a class="airforce-min" href="/jura/nase-e-shopy#airforce">
							<span class="top">
									<p class="top-img">
										<img style="float: left; width: 60px; " src="/images/footer/f181tlc45bkx1362.jpg"> 
									</p>  
							 		<p class="top-text">Internetový obchod, který Vám nabízí široký sortiment odsavačů par. Nabízí odborné poradenství při nákupu digestoří.
										   
									 </p>         
								</span>
							</a></div>  
							<div class="logo-item"><a class="elica-min" href="/jura/nase-e-shopy#elica">
							<span class="top">
									<p class="top-img">
										<img style="float: left; width: 60px; " src="/images/footer/3310-1312488952.jpg"> 
									</p>  
							 		<p class="top-text">Jsme specializovaným prodejcem italských odsavačů par Elica. Máme vyškolený tým obchodníků, který své práci rozumí a rád zodpoví veškeré Vaše dotazy ohledně funkčnosti přístrojů i možných variant zapojení.
									 </p>         
								</span>
							</a></div>
							<div class="logo-item"><a class="lord-min" href="/jura/nase-e-shopy#lord">
							<span class="top">  
									<p class="top-img">
										<img style="float: left; width: 60px; " src="/images/footer/586840.jpg"> 
									</p>  
							 		<p class="top-text">Představujeme internetový obchod www.vipelektro.cz, který nabízí nákup pračky, myčky sušičky, trouby či varné desky. Výrobky LORD mají kromě skvělého designu také vysokou německou kvalitu.
										   
									 </p>         
								</span>
							</a></div>
							<div class="logo-item"><a class="laura-min" href="/jura/nase-e-shopy#lord">
							<span class="top">     
									<p class="top-img">               
										<img style="float: left; width: 60px; " src="/images/footer/laurastar-prod.jpg"> 
									</p>  
							 		<p class="top-text">Jsme specializovaným prodejcem vysoce kvalitních švýcarských žehlicích systémů a parních generátorů LAURASTAR, které jsou určeny jak pro domácí, tak pro profesionální použití.
										   
									 </p>         
								</span>
							</a></div>      
					</div>             
					<div class="specshop-wrapper">      
                     <span class="spant2">OVĚŘENÝ ESHOP</span>
						<p>         
							<strong><?=helper_FrontEnd::price($this->historyBasketCount ) ?> zákazníků</strong> = záruka bezpečného nákupu i pro Vás!
						</p>
						<p>
							Tento obchod je součástí sítě specializovaných obchodů <strong>specSHOP.cz</strong>
						</p>
								<?$mImportHeurekaReviews = new module_Reviews($this);?>
<?
$this->ListingItemsCount= $mImportHeurekaReviews->getCountReview();
helper_Listing::init($this);
list($total1,$data) = $mImportHeurekaReviews->show($this->listingSQLStartPos, 12);
list($total,$data1) = $mImportHeurekaReviews->show(0, 55555555555555);?>     
<div class="left-side-bar-wrapper rating-shop rating-shop-footer" >       
   	<p class="f-left"><strong>Hodnocení <span>Svycarskekavovary.cz</span></strong></p>  
	<div class="rating-content all">	
    	Celkem <span><span><?=$total->total?></span> známka</span>/
   		<span itemprop="reviewCount"><?=$total->count?></span> hlasů):       
  		<div class="content-right">           
		  <span class="emptyStarsMini marRight3 i-block vAlingMid ">        
					<span class="i-block fullStarsMini" style="width:<?=$total->total*20.8?>px;"></span>   </span>   
		  
		</div>      
	</div>            
</div>         
</div>  
	</div>
			</div>  
		</div>                  
	</div> 
</div>   
<?=$this->render('parts/cookies.phtml'); ?>
</div>
  
            