<div id="footer">
	  <div class="inner">
	  	<div class="container">
                    <ul>
                        <li><a class="logo" href="/jura"></a></li>
                        <li>Svycarskekavovary.cz © 2012</li>
                        <li>-</li>  
                        <li><a href="/jura/kontakty">Provozovatel</a></li> 
                    </ul>
                </div>      
                </div>
	<div class="container"> 
 <div class="clear"></div> 
                  <div id="niceFooter"> 
                  	<div id="niceFooter1" class="left niceFoItem">
                  		<h6>ESHOP SVYCARSKEKAVOVARY.CZ</h6>  
                  		<p><a rel="nofollow" href="<?= $this->dopravaNode->path?>"><?= $this->dopravaNode->title?></a></p>
                  		<p><a rel="nofollow" href="/jura/obchodni-podminky">Obchodní podmínky</a></p>
                  		<p><a rel="nofollow" href="/jura/zpracovani-osobnich-udaju">Zpracování osobních údajů</a></p>
                  		<p><a rel="nofollow" href="/jura/kontakty">Kontakty</a></p>  
                  	</div> 
                  	<div id="niceFooter2" class="left niceFoItem">  
                  		<h6>PROČ NAKUPOVAT U NÁS</h6>
                  		<p><a rel="nofollow" href="/jura/bezpecny-nakup">Bezpečný nákup</a></p>
                  		<p><a rel="nofollow" href="/jura/bezpecny-nakup#zarakt">Záruka aktivní řešení reklamací</a></p>
                  		<p><a rel="nofollow" href="/jura/bezpecny-nakup#kom">Záruka aktivní komunikace</a></p>
                  		<p><a rel="nofollow" href="/jura/bezpecny-nakup#zarprod">Záruka původu produktů</a></p>
                  		<p><a rel="nofollow" href="/jura/bezpecny-nakup#vrac">Záruka vrácení pěněz</a></p>
                  		<p><a rel="nofollow" href="/jura/bezpecny-nakup#kval">Záruka kvality</a></p>
                  		<p><a rel="nofollow" href="/recenze">Ověřeno zákazníky</a></p>
                  		<p><a rel="nofollow" target="_blank" href="/data/dtest_jura.pdf">Validace e-shopu <span class="red"><strong>dTest</strong></span></a></p>
                  	</div>
                  	<div id="niceFooter3" class="left niceFoItem">
                  		<h6>RYCHLÉ PLATBY</h6>
                  		<div class="tableNiceFooter">   
                  				<div>
                  					<img data-LL-src="/images/cesSpor.png" alt="Česká Spořitelna" title="Česká Spořitelna">
                  					<noscript><img src="/images/cesSpor.png" alt="Česká Spořitelna" title="Česká Spořitelna"></noscript>
                  					</div>
                  				<div><img data-LL-src="/images/kb.png" alt="Komerční banka" title="Komerční banka">
                  					<noscript><img src="/images/kb.png" alt="Komerční banka" title="Komerční banka"></noscript></div> 
                  				<div>
                  					<img data-LL-src="/images/fiio.png" alt="Fio" title="Fio">
                  					<noscript><img src="/images/fiio.png" alt="Fio" title="Fio"></noscript></div>
                  				<div>
                  					<img data-LL-src="/images/Era.png" alt="ERA" title="ERA">
                  					<noscript><img src="/images/Era.png" alt="ERA" title="ERA"></noscript></div>
                  				<div>
                  					<img data-LL-src="/images/csob.png" alt="ČSOB" title="ČSOB">
                  					<noscript><img src="/images/csob.png" alt="ČSOB" title="ČSOB"></noscript></div>
                  				<div>
                  					<img data-LL-src="/images/raiBank.png" alt="Raiffeisen BANK" title="Raiffeisen BANK">
                  					<noscript><img src="/images/raiBank.png" alt="Raiffeisen BANK" title="Raiffeisen BANK"></noscript></div>
                  					<img data-LL-src="/images/MasterCard.png" alt="MasterCard" title="MasterCard">
                  				<div><noscript><img src="/images/MasterCard.png" alt="MasterCard" title="MasterCard"></noscript></div>
                  				<img data-LL-src="/images/Maestro.png" alt="Maestro" title="Maestro">
                  				<div><noscript><img src="/images/Maestro.png" alt="Maestro" title="Maestro"></noscript></div>
                  		</div>
                  	   <div class="clear"></div>  
                  	<span>SPLÁTKOVÝ PRODEJ</span>
                  	   <div class="spacer10"></div>  
                  	<div class="pull-left">   
                  			<p> 
                  					<a rel="nofollow" href="/" id="kalSplatFooter" onclick="window.open('http://www.iplatba.cz/kalkulacka-nakupu-na-splatky/?cenaZbozi=19999&amp;idObchodu=MTUwMDI=','iPlatba','width=600,height=600,menubar=no,toolbar=no')">
									Splátkový kalkulátor</a></p> 
                  		</div> 
                  		<div class="pull-left">   
                  				<a href="#"><img data-LL-src="/images/cofidisFooter.png" alt="Splátkový kalendář Cofidis" title="Splátkový kalendář Cofidis"><noscript><img src="/images/cofidisFooter.png" alt="Splátkový kalendář Cofidis" title="Splátkový kalendář Cofidis"></noscript></a>
                  		</div>
                  	</div>
                  	<div id="niceFooter4" class="left"> 
                  		<div class="left">
                  			<h6>OVĚŘENÝ ESHOP</h6>
                  			<p><span class="red"><strong><?=helper_FrontEnd::price($this->historyBasketCount)?></strong></span> zákazníků = záruka<br />
                  				<a rel="nofollow" href="/jura/bezpecny-nakup"><span class="red">bezpečného nákupu</span></a> i pro<br />
                  				Vás!
                  			</p>
                  		</div> 
                  		<div class="left" id="specsFootLogo"> 
                  			<a rel="nofollow" target="_blank" href="http://www.specshop.cz/">
                  				<noscript><img data-LL-src="/images/specFooter.png" alt="specSHOP.cz" title="specSHOP.cz" /><img src="/images/specFooter.png" alt="specSHOP.cz" title="specSHOP.cz" /></noscript>
                  				</a>
                  		</div>
                  		<div class="clear"></div> 
                  		<p>Tento obchod je součástí sítě <br />        
                  			specializovaných obchodů <a target="_blank" href="http://www.specshop.cz/">specSHOP.cz</a></p>  
                  		<div class="clear"></div> 
                  		<div class="left sp-f"><img data-LL-src="/images/spolehliva-firma-65x65.png" alt="Spolehlivá firma 2019" title="Spolehlivá firma 2019"/><noscript><img src="/images/spolehliva-firma-65x65.png" alt="Spolehlivá firma 2019" title="Spolehlivá firma 2019"/></noscript></div>             
                  		<div class="left"><img data-LL-src="/images/kvalFirma.png" alt="Kvalitní firma" title="Kvalitní firma" /><noscript><img src="/images/kvalFirma.png" alt="Kvalitní firma" title="Kvalitní firma" /></noscript></div>   
                  		<div class="left"><img data-LL-src="/images/zeleFirma.png" alt="Zelená firma" title="Zelená firma"/><noscript><img src="/images/zeleFirma.png" alt="Zelená firma" title="Zelená firma"/></noscript></div
                  		<div class="clear"></div>  
                  	</div>
                  </div>  
                  </div>    
                  <?=$this->render('parts/cookies.phtml'); ?> 
            </div>
     