			
			<?php foreach ($this->messages as $m):
				switch($m{0}){
					case 'e':
						$class = 'errorm';
						$title = 'Upozornìní';
						break;						
					
					case 'i':
						$title = 'Informace';
						$class = 'infom';
						break;			
						
				}
				$messages .= substr($m,2).'<br>';				
			?>				
					
			<?php endforeach; ?>			
			<div class="message <?=$class?>"><?php echo $messages ?> </div>	
				