
        <div class="flyout-content bee__flyout__content bee__flyout__part bee__flyout__content--full-width">
<div class="bee__flyout__content--inner">

<div>
<dl class="bee__flyout__content-list">

<span>
<dd class="bee__flyout__label">Rozměry - Otevřen&yacute; poklop (centimetry)</dd>
<dt class="bee__flyout__value">141cm V x 65cm &Scaron; x 76cm H</dt>
</span>

<span>
<dd class="bee__flyout__label">Rozměry - Zavřen&yacute; poklop (centimetry)</dd>
<dt class="bee__flyout__value">100cm V x 65cm &Scaron; x 76cm H</dt>
</span>

<span>
<dd class="bee__flyout__label">Průměr (centimetry)</dd>
<dt class="bee__flyout__value">57 </dt>
</span>

<span>
<dd class="bee__flyout__label">Celkov&aacute; plocha (centimetry) na grilov&aacute;n&iacute;</dd>
<dt class="bee__flyout__value">2342 cm&sup2; </dt>
</span>

<span>
<dd class="bee__flyout__label">Druh paliva</dd>
<dt class="bee__flyout__value">Dřevěn&eacute; uhl&iacute; </dt>
</span>

<span>
<dd class="bee__flyout__label">SKELN&Yacute;MI VL&Aacute;KNY VYZTUŽEN&Eacute; NYLONOV&Eacute; MADLO KOTLE</dd>
<dt class="bee__flyout__value">1 </dt>
</span>

<span>
<dd class="bee__flyout__label">Gumov&aacute; kola s průměrem 20 cm odoln&aacute; vůči vlivům počas&iacute;</dd>
<dt class="bee__flyout__value">2 </dt>
</span>

<span>
<dd class="bee__flyout__label">H&aacute;čky na n&aacute;čin&iacute;</dd>
<dt class="bee__flyout__value">2 </dt>
</span>

<span>
<dd class="bee__flyout__label">Nerezavěj&iacute;c&iacute; hlin&iacute;kov&eacute; větrac&iacute; průduchy</dd>
<dt class="bee__flyout__value">1 </dt>
</span>

<span>
<dd class="bee__flyout__label">Palivov&eacute; n&aacute;doby Char-Basket</dd>
<dt class="bee__flyout__value">2 </dt>
</span>

</dl>
</div>


<div>
<ul class="bee__flyout__content-list--multi">

<li class="bee__flyout__content-list">
<span>
<dl>

<dt class="bee__flyout__content-list-item">
<div class="bee__flyout__label bee__flyout__label-heading bee__flyout__label--fullwidth">
Vlastnosti
</div>
</dt>



<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Gourmet BBQ System odkl&aacute;pěc&iacute; grilovac&iacute; ro&scaron;t z nerez oceli</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Ro&scaron;t na dřevěn&eacute; uhl&iacute; z kvalitn&iacute; oceli</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Porcel&aacute;nem smaltovan&yacute; kotel a poklop</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Vestavěn&yacute; teploměr v poklopu</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">SPODN&Iacute; DR&Aacute;TĚN&Yacute; TROJ&Uacute;HELN&Iacute;K</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Vyměniteln&yacute;, vysokokapacitn&iacute; popeln&iacute;k</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Nerezov&yacute; čistic&iacute; syst&eacute;m One-Touch se silikonov&yacute;m držadlem</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Mont&aacute;ž nohy na stlačn&yacute; kol&iacute;k</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Odměrka na brikety souč&aacute;st&iacute; balen&iacute;</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">VĚT&Scaron;&Iacute; MADLO PRŮDUCHU POKLOPU</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">Drž&aacute;k pro zař&iacute;zen&iacute; iGRILL</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">MASIVN&Iacute; MADLO POKLOPU</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth"> PORCEL&Aacute;NEM SMALTOVAN&Aacute; KRUHOV&Aacute; PŘEP&Aacute;ŽKA NA DŘEVĚN&Eacute; UHL&Iacute;</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">NEREZOV&Yacute; DIFUZ&Eacute;R</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">PANT POKLOPU Z NEREZOV&Eacute; OCELI S JEDNODUCH&Yacute;M ODN&Iacute;M&Aacute;N&Iacute;M POKLOPU</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">PRŮDUCHY V KOTLI NASTAVITELN&Eacute; NA UZEN&Iacute;</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">GRILOV&Aacute;N&Iacute; 3 V 1: GRILUJTE, OP&Eacute;KEJTE A UĎTE NA PŘ&Iacute;M&Eacute;M I NEPŘ&Iacute;M&Eacute;M Ž&Aacute;RU</div>
</dd>

<dd class="bee__flyout__content-list-item">
<div class="bee__flyout__value bee__flyout__label--fullwidth">SOUČ&Aacute;ST&Iacute; JE LITINOV&Yacute; RO&Scaron;T SEAR GRATE GBS</div>
</dd>


</dl>
</span>
</li>

</ul>
</div>

</div>
</div>
</li>

