<?php  
$items = $this->mEshop->basket->getItems();
$voucher = $this->mEshop->basket->voucher;
$itemsCount = count($items); 
$sumAll = $discount = 0;
$delivery = $this->mEshop->basket->getDeliveryPrice2();
$payment = $this->mEshop->basket->getPaymentPrice();
$mp = new module_Eshop_PriceCalc($voucher, $items, $delivery, $payment); 
if($_GET['ted'])
{
	pr($mp->delivery);             
}     
                    		
?>
          <div id="priceBlock">
            <p class="head">Shrnutí objednávky</p>
            <p>Cena zboží bez DPH<span class="fs14 pull-right"><?=helper_FrontEnd::price($mp->sumBezDph)?> Kč</span></p>
            <p>DPH  <span class="fs14 pull-right blockDisplay tAlignRight"><?=helper_FrontEnd::price($mp->dph)?> Kč</span></p>
            <? if($mp->delivery):?>
            <p>Doprava s DPH <?=$this->dph?>%<br><span><?=helper_FrontEnd::price($mp->delivery)?> Kč</span></p>
            <? endif;?>  
			<? if($mp->payment):?>
            <p>Platba s DPH <span><?=helper_FrontEnd::price($mp->payment)?> Kč</span></p>
            <? endif;?> 
			<? if($voucher):?>
			<p>Mezisoučet<span><?=helper_FrontEnd::price($mp->subtotal)?> Kč</span></p>
            <p>Kupón <?=Utils::getHelpIco(htmlspecialchars($mp->helpText))?><span class="fs14 fRight blockDisplay tAlignRight">- <?=$mp->voucher['value']?></span></p>
            <? endif;?>
            <p class="total"><strong>Celkem k úhradě</strong><br><span id="shopPrice" class="pull-right"><strong><?=helper_FrontEnd::price($mp->sum)?> Kč</strong></span></p>
     </div>  