<div id="page" class="hp">  
		<div id="leftPage">

			<?if(!$this->disableLeft):?> 
                        <? if(!$this->disableH1):?>
							<h1><?=$this->pageTitleRaw?></h1> 
						<? endif;?> 
                	<?=$this->page;?>  
                   	 <div class="clear"></div>
	               <?else:?>  
	              <?=$this->page;?>	 
                   	 <div class="clear"></div>
			<?endif;?>
          </div>  
          
          <div id="rightPage">  
           	 <?=$this->pageRight;?>  
               
                	<div class="clear"></div>   
			</div>
	</div> 
                 
                 