<?= $this->html ?> 

<?
$images = helper_FrontEnd::getResizedPhotos($this->photos, 'pThumb', 'pFull'); 	
$keys = array_keys($this->photos);                                           
shuffle($images);

foreach ($images as $img):  
	$f = next($keys); 
	$full = $img['path'];
	$descr = $img['name'];        
	$fullImg = $img['fullPath']; 		  
	$z++; 
	?>                          
		<div class="gimg <?=($z%3==0?'last':'')?>">  
			<a target="_blank" rel="[images]" title="<?=$descr?>" id="mb<?=$z?>" class="mbb" href="<?=$fullImg?>" target="_blank"><img src="<?=$full?>" alt="<?=$descr?>" title="<?=$descr?>" /></a>
			<div class="multiBoxDesc mb<?=$z?> mbHidden"> </div>	
		</div>  
<? endforeach; ?>    
 
	<div class="spacer10"></div> 
	
	<script type="text/javascript"> 	 
	window.addEvent('domready', function(){
		box = new multiBox({
			mbClass: '.mbb',//class you need to add links that you want to trigger multiBox with (remember and update CSS files)
			container: $(document.body),
			descClassName: 'multiBoxDesc',//the class name of the description divs
			path: './Files/',//path to mp3 and flv players
			useOverlay: true,//use a semi-transparent background. default: false;
			maxSize: {w:600, h:400},//max dimensions (width,height) - set to null to disable resizing
			addDownload: false,//do you want the files to be downloadable?
			pathToDownloadScript: './Scripts/forceDownload.asp',//if above is true, specify path to download script (classicASP and ASP.NET versions included)
			addRollover: false,//add rollover fade to each multibox link
			addOverlayIcon: false,//adds overlay icons to images within multibox links
			addChain: false,//cycle through all images fading them out then in
			recalcTop: false,//subtract the height of controls panel from top position
			addTips: false,//adds MooTools built in 'Tips' class to each element (see: http://mootools.net/docs/Plugins/Tips)
			autoOpen: 0//to auto open a multiBox element on page load change to (1, 2, or 3 etc)
		});
	});
	</script>
	<? 
										if(count($this->documents)):
											?>
											 <div id="dl">
												<h4>Ke stažení:</h4>
												<?  
												foreach ($this->documents as $filepath => $name): 
													$fullpath = content_SFSFile::getFileFullPath($filepath);
													$ico = Utils::getFileIcoImage($fullpath);
													?>	
													<?= $ico ?> 
													<a title="Otevřít '<?= $name ?>' do nového okna" target="_blank" href="<?=$filepath?>"> <?= $name ?> <i><?=Utils::getWebFileSize($fullpath)?></i></a> <br />														
																	
													<? 
												endforeach; 	
												?>
											</div>
											<?			
										endif;	
										?>	