<script src="/js/prototype.js" type="text/javascript"></script>
<script src="/js/scriptaculous.js?load=effects,builder" type="text/javascript"></script>
<script src="/js/lightbox.js" type="text/javascript"></script>
<div id="txtPart">
	<?= $this->html ?>
</div>

<?$images = helper_FrontEnd::getResizedPhotos($this->photo, 'cThumb', 'pFull');
$image = $images[0];?> 	          
<div class="photos">              

<div class="gimg ">
			<a target="_blank" rel="[images]" id="mb1" class="mbb" href="<?=$image['fullPath']?>"><img src="<?=$image['path']?>" alt="<?=$image['name']?>" title="<?=$image['name']?>" /></a>
			<div class="multiBoxDesc mbb1"><?=$image['name']?></div>	
		</div>   
</div>

<script type="text/javascript"> 	
		var box = {};   
		window.addEvent('domready', function(){
			box = new multiBox('mbb', {descClassName: 'multiBoxDesc', useOverlay: true}); 
		}); 
</script> 
