<?$mImportHeurekaReviews = new module_Reviews($this);?>
<?
$this->ListingItemsCount= $mImportHeurekaReviews->getCountReview();
helper_Listing::init($this);
list($total1,$data) = $mImportHeurekaReviews->show($this->listingSQLStartPos, 12);
list($total,$data3) = $mImportHeurekaReviews->show(0, 55555555555555);
?> 

<h1>Hodnocení <?=str_replace('https://www.','', Utils::getWebUrl());?></h1>
<div id="revSummary">
				<p><strong>Celkové hodnocení:</strong></p>
				<div class="emptyStars">
					<div style="width:<?=$total->total*27.6?>px;" class="fullStars"></div>
				</div>
				<div class="clear"></div>
				<p>Doba doručení:</p>
				<div class="emptyStars">
					<div style="width:<?=$total->delivery*27.6?>px;" class="fullStars"></div>
				</div>
				<div class="clear"></div>
				<p>Doprava:</p>
				<div class="emptyStars">
					<div style="width:<?=$total->transport*27.6?>px;" class="fullStars"></div>
				</div>
				<div class="clear"></div>
				<p>Přehlednost obchodu:</p>
				<div class="emptyStars">
					<div style="width:<?=$total->webUsa*27.6?>px;" class="fullStars"></div>
				</div>
				<div class="clear"></div>
				<p>Komunikace:</p>
				<div class="emptyStars">
					<div style="width:<?=$total->communication*27.6?>px;" class="fullStars"></div>
				</div>
				<div class="clear"></div>
				
</div>	
<div id="revSummaryText">      
<?=$this->content->getPropertyByName('html')->value?>
<a href="https://obchody.heureka.cz/svycarskekavovary-cz-jura/recenze/overene" target="_blank" rel="nofollow"><img src="/images/czHeurekaOvereno.jpg" width="355"></a></div>	
<div class="line"></div>
<div class="spacer10"></div>	
<h3>Recenze uživatelů:</h3>
<div class="spacer10"></div>	
<?
if($data):
$inc = 0;
foreach ($data as $item):
		$inc++;
			if($inc > 11){
				break;
			}
			if(!$item['date'])
				continue;
			$name = '';?>
			<div class="revName fstRev">
			<span class="userIcon"></span>
			<?$name = $item->name?$item['name']:'Ověřený zákazník';?>
			<span><?=$name?></span>			
			 
			</div>
			<div class="revName">
				<div class="emptyStars">
					<div style="width:<?=$item['total_rating']*28?>px;" class="fullStars"></div>
				</div>
				<table>
					<?if($item['pros']):?>
					<tr>
						<td><span class="plus">+</span></td>
						<td><span class="plus"><?=$item['pros']?></span></td>
					</tr>
					<?endif?>
					<?if($item['cons']):?>
					<tr>
						<td><span class="minus">-</span></td>
						<td><span class="minus"><?=$item['cons']?></span></td>
					</tr>
					<?endif?>
					<?if($item['reaction']):?>
					<tr>
						<td>?</td>
						<td><?=$item['reaction']?></td>
					</tr>
					<?endif?>
					<?if($item['summary']):?>
					<tr>
						<td></td>
						<td colspan="1"><?=$item['summary']?></td>
					</tr>
					<?endif?>
				</table>
			</div>	
			<div class="revText">
				<p>celkem:</p>
				<div class="emptyStarsMini">
					<div style="width:<?=$item['total_rating']*19?>px;" class="fullStarsMini"></div>
				</div>
				<p>doručovací doba:</p>
				<div class="emptyStarsMini">
					<div style="width:<?=$item['delivery']*19?>px;" class="fullStarsMini"></div>
				</div>
				<p>doprava:</p>
				<div class="emptyStarsMini">
					<div style="width:<?=$item['transport']*19?>px;" class="fullStarsMini"></div>
				</div>
				<p>přehlednost:</p>
				<div class="emptyStarsMini">
					<div style="width:<?=$item['webUsa']*19?>px;" class="fullStarsMini"></div>
				</div>
				<p>komunikace:</p>
				<div class="emptyStarsMini">
					<div style="width:<?=$item['communication']*19?>px;" class="fullStarsMini"></div>
				</div>
				
			</div>
			<div class="line"></div>	
			
		<?endforeach;
endif;
?>