<?
if(isset($this->input->send) || $this->input->send_x){
	$webForm = new module_WebForm($this->input);	
	
	$text = '
		<h2 style="color:#0f4096; font-size: 12px;">Dotaz z webu</h2>
		<table style="font-size: 11px; color: #708490;">
			<tr><td>Jméno:</td><td>' . $webForm->fullname . '</td></tr>
			<tr><td>Email:</td><td>' . $webForm->email . '</td></tr>
			<tr><td>Telefon:</td><td>' . $webForm->input->phone . '</td></tr>
			<tr><td>Zpráva:</td><td>' . nl2br($webForm->input->message) . '</td></tr>
		</table>				
		<p>
	';
	
	
	list($state, $messages) = $webForm->sendEmail($text);
	Helpers::addMessage($state, $messages, $this);
}

$this->formSubject = 'WWW: ' . $this->curentNode->title;
?>
<?=$this->render('templates/Contents/ContactForms/Simple.phtml')?>