<?php 
$this->obsahClass = $this->znacky[$this->node->nodeId][2];
$logo = $this->znacky[$this->node->nodeId][1];
$this->disableH1 = true;      
?> 
          <div id="popis">
            <div id="opis"> 
              <h1><?=$this->pageTitleRaw?></h1>
              <?=$this->pageText?>  
            </div> 
            <div id="znackaLogo"><img src="<?=$logo?>" alt="<?=$this->pageTitleRaw?>"><a href="#">www.tefal.cz</a></div>
          </div>  
          <div id="contentSorting">
            <h2>Výrobky značky <?=$this->pageTitleRaw?> naleznete v těchto kategoriích:</h2>
            <div>
              <p>Do Kuchyně</p>
              <ul class="fst">
                <li><a href="#">Espressa a kávovary</a></li>
                <li><a href="#">Rychlovarné konvice</a></li>
                <li><a href="#">Elektrické fritézy</a></li>
              </ul>
              <ul>
                <li><a href="#">Tyčové mixéry</a></li>
                <li><a href="#">Parní hrnce</a></li>
                <li><a href="#">Sendvičovače</a></li>
              </ul>
              <ul>
                <li><a href="#">Tyčové mixéry</a></li>
                <li><a href="#">Parní hrnce</a></li>
                <li><a href="#">Sendvičovače</a></li>
              </ul>
              <ul>
                <li><a href="#">Tyčové mixéry</a></li>
                <li><a href="#">Parní hrnce</a></li>
                <li><a href="#">Sendvičovače</a></li>
              </ul>
            </div>
            <div>
              <p>Nádobí a stolování</p>
              <ul class="fst">
                <li><a href="#">Nepřilnavé nádobí</a></li>
                <li><a href="#">Nerezové nádobí</a></li>
                <li><a href="#">Tlakové hrnce</a></li>
              </ul>
              <ul>
                <li><a href="#">Nádobí Ingenio</a></li>
                <li><a href="#">Nože</a></li>
                <li><a href="#">Pečící formy a pekáče</a></li>
              </ul>
            </div>
            <div> 
              <p>Osobní péče</p>
              <ul class="fst">
                <li><a href="#">Péče o dítě</a></li>
                <li><a href="#">Osobní váhy</a></li>
              </ul>
            </div>
          </div>
          <div id="products">
            <h3>Nejprodávanější produkty značky <?=$this->pageTitleRaw?></h3>
            <div class="fst">
              <p><a href="#">KRUPS KP2102 Nescafé Dolce Gusto - Smetanové</a></p>
              <div class="img"><img src="/images/img_final_znacka.jpg" alt="Obr" width="220" height="184"></div>
              <div class="podrobnosti">
                <p class="skladem">skladem<span>Příští den u Vás</span></p>
                <div class="buy">
                  <p>2 695 Kč</p>
                  <a href="#">&nbsp;</a></div>
              </div>
            </div>
            <div>
              <div class="productBorder"></div>
              <div class="productInner">
                <p><a href="#">KRUPS KP2102 Nescafé Dolce Gusto - Smetanové</a></p>
                <div class="img"><img src="/images/img_final_znacka.jpg" alt="Obr" width="220" height="184"></div>
                <div class="podrobnosti">
                  <p class="neniSkladem">Není skladem<span>Dodání do 10 dnu</span></p>
                  <div class="buy">
                    <p>2 695 Kč</p> 
                    <a href="#">&nbsp;</a></div>
                </div>
              </div>
              <div class="productBorder"></div>
            </div>
            <div class="lst">
              <p><a href="#">KRUPS KP2102 Nescafé Dolce Gusto - Smetanové</a></p>
              <div class="img"><img src="/images/img_final_znacka.jpg" alt="Obr" width="220" height="184"></div>
              <div class="podrobnosti">
                <p class="skladem">skladem<span>Příští den u Vás</span></p>
                <div class="buy">
                  <p>2 695 Kč</p>
                  <a href="#">&nbsp;</a></div>
              </div>
            </div>
            <a class="dop" href="#">Další oblíbené produkty</a> </div>
         