 
	        	 <div id="tabsleft" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1">Menu</a></li> 
				    </ul> 
				    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel">  
						<div>
						<?php   
						 
						$menu = array(); 
						$menu[] = array(
							'title' => 'Odeslané emaily',  
							'icon' => 'mail-open',
							'onclick' => $this->url(array('action' => 'index', 'ajax' => '0', 'id' => '0')),
							'isSelected' => $this->curentAction=='index',  
							'params' => ' ' 
						); 
						$menu[] = array(
							'title' => 'Odeslat newsletter',
							'icon' => 'mail-closed',
							'onclick' => $this->url(array('action' => 'send', 'ajax' => '0', 'id' => '0')),
							'isSelected' => $this->curentAction=='send',
							'params' => ' id="xyy" ',
							'children' => array( 
							)
						);
						$menu[] = array( 
							'title' => 'Odeslat produktový newsletter',
							'icon' => 'mail-closed', 
							'onclick' => $this->url(array('action' => 'newsletter', 'ajax' => '0', 'id' => '0')),
							'isSelected' => $this->curentAction=='newsletter',
							'params' => ' id="xyy" ',
							'children' => array(  
							)
						); 
						$menu[] = array(
							'title' => 'Správa příjemců',
							'icon' => 'person',
							'onclick' => $this->url(array('action' => 'users', 'ajax' => '0', 'id' => '0', 'filter2' => '0')),
							'isSelected' => $this->curentAction=='users',
							'params' => ' ', 
							'children' => array( 
							) 
						);
						?>
						
						<ul id="leftmenu" class="ui-menu ui-widget ui-widget-content ui-corner-all ui-menu-icons" role="menu">   
							<? 
							foreach ($menu as $ii => $item):
								$hasChildren = count($item['children']) && is_array($item['children']); 
								?>
							    <li class="ui-menu-item" role="presentation">
							    	<a class="ui-corner-all<?=($item['isSelected']?' clicked':'')?>" href="<?=$item["onclick"]?>"><span <?=(!$item["icon"]?'':'class="ui-icon  ui-icon-' . $item["icon"] . '"')?>></span><?=$item["title"]?></a>
							    	<?if($hasChildren):?>
							    	<ul style="display: none;"> 
							    	<? foreach ($item['children'] as $iii => $item2):?>
							    	<a <?=($item2['isSelected']?'class="clicked"':'')?> href="<?=$item2["onclick"]?>"><span <?=(!$item2["icon"]?'':'class="ui-icon  ui-icon-' . $item2["icon"] . '"')?>></span><?=$item2["title"]?></a>
							    	<? endforeach;?> 
							    	</ul>
							    	<? endif;?>
							    </li>
						    <? endforeach;?> 
						</ul> 
						
						 <script>
						    $(function() { 
						        $( "#leftmenu" ).menu();
						    }); 
						    </script>  
						</div>
					</div> 
				</div> 
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsleft" ).tabs();
			    }); 
			    </script> 