 			 
	        	<div id="accordionRight">
	        		<h3>Statistiky stránek</h3> 
	        		<div>  
						 
					<table cellspacing="0" cellpadding="0" border="0">
						<tbody><tr><td class="awsm"><a href="/statsframe?framename=mainright#top" target="mainright">Souhrn</a></td></tr>
						<tr><td class="awsm" width="240"><b>Kdy:</b></td>
						</tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#month" target="mainright">Měsíční přehled</a></td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#daysofmonth" target="mainright">Denní přehled</a></td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#daysofweek" target="mainright">Dny v týdnu</a></td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#hours" target="mainright">Hodiny</a></td></tr>
						<tr><td class="awsm" width="240"><b>Kdo:</b></td>
						</tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#countries" target="mainright">Země</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=alldomains" target="mainright">Úplný seznam</a>
						</td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#visitors" target="mainright">Počítače</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=allhosts" target="mainright">Úplný seznam</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=lasthosts" target="mainright">Poslední návštěvy</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=unknownip" target="mainright">Nepřeložené IP adresy</a>
						</td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#robots" target="mainright">Roboty</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=allrobots" target="mainright">Úplný seznam</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=lastrobots" target="mainright">Poslední návštěvy</a>
						</td></tr> 
						<tr><td class="awsm"><b>Prohlížení:</b></td>
						</tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#sessions" target="mainright">Délka návštěv</a></td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#filetypes" target="mainright">Typy souborů</a></td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#urls" target="mainright">Zobrazeno</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=urldetail" target="mainright">Úplný seznam</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=urlentry" target="mainright">Vstup</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=urlexit" target="mainright">Odchod</a>
						</td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#os" target="mainright">Operační systémy</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=osdetail" target="mainright">Verze</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=unknownos" target="mainright">Neznámé</a>
						</td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#browsers" target="mainright">Prohlížeče</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=browserdetail" target="mainright">Verze</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=unknownbrowser" target="mainright">Neznámé</a>
						</td></tr>
						<tr><td class="awsm" width="240"><b>Odkazující stránky:</b></td> 
						</tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#referer" target="mainright">Původ</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=refererse" target="mainright">Odkazující vyhledávače</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=refererpages" target="mainright">Odkazující stránky</a>
						</td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#keys" target="mainright">Vyhledávání</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=keyphrases" target="mainright">Hledaná&nbsp;slovní&nbsp;spojení</a>
						</td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=keywords" target="mainright">Hledané&nbsp;výrazy</a>
						</td></tr>
						<tr><td class="awsm" width="240"><b>Ostatní:</b></td>
						</tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#misc" target="mainright">Různé</a></td></tr>
						<tr><td class="awsm"><a href="/statsframe?framename=mainright#errors" target="mainright">Stavové kódy HTTP</a></td></tr>
						<tr><td class="awsm"> &nbsp; <img height="8" width="9" src="/awstatsicons/other/page.png" alt="..."> <a href="/statsframe?framename=mainright&amp;output=errors404" target="mainright">Nenalezené stránky</a>
						</td></tr>
						</tbody></table>

					</div>     
	        		<h3>Nápověda</h3> 
	        		<div>  
	        			<?=$this->helpContent?>
	        		</div>   
	        	</div> 
	        		<script>
				    $(function() {
				        $( "#accordionRight" ).accordion({ 
				            heightStyle: "content"
				        });
				    });
				    </script> 