<?if($this->node->nodeId == 76869):?>
	<div class="container-eshop">      
		<img class="spec-logo" alt="logo Specshop s.r.o" src="/images/footer/logo-specik.png">
		<ul>       
			<li>Jsme síť specializovaných eshopů.</li>   
			<li>Máme špičkové vyškolené prodejce a zboží SKLADEM</li> 
			<li>Individuální přístup, kvalitní autorizovaný servis</li>
			<li>8 eshopů v České republice</li>
			<li>6 eshopů na Slovensku</li>        
			<li>Maximální spokojenost zákazníků</li>  
		</ul>  
		<div class="clear">&nbsp;</div>  
		<div class="item-eshop" id="jura">       
			<a href="https://www.svycarskekavovary.cz/jura" class="item-eshop-link">
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo jura"></span>
					<span class="item-eshop-text">Autorizovaný prodejce JURA</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/jura-e8-front-min.jpg">
				</span>
				<p><strong>www.svycarskekavovary.cz/jura</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="nivona">   
			<a href="https://www.nivona-eshop.cz" class="item-eshop-link">
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo nivona"></span>
					<span class="item-eshop-text">Specializovaný eshop NIVONA</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/841.jpg">
				</span>
				<p><strong>www.nivona-eshop.cz</strong></p>	
			</a>  
		</div>
		<div class="item-eshop" id="liebher">   
			<a href="https://www.topchlazeni.cz" class="item-eshop-link">
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo lie"></span>
					<span class="item-eshop-text">Chlazení LIEBHERR - Eshop</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/gnp2855-20_sod.jpg">
				</span>
				<p><strong>www.topchlazeni.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="chlad">   
			<a href="https://www.chladnickanavino.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo chlad"></span>
					<span class="item-eshop-text">Speciálka na domácí vinotéky</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/dunavox-dx-30.80.jpg">
				</span>
				<p><strong>www.chladnickanavino.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="faber">   
			<a href="https://www.faber-eshop.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo faber"></span>
					<span class="item-eshop-text">Italské digestoře FABER</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/FABER_Stilo_SP_SRM_X_A90-1488.jpg">
				</span>
				<p><strong>www.faber-eshop.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="airforce">   
			<a href="https://www.airforce-eshop.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo airfor"></span>  
					<span class="item-eshop-text">Luxusní odsavače Airforce</span>
				</span>  
				<span class="item-eshop-link-content-h">     
					<img src="/images/footer/f181tlc45bkx1362.jpg">
				</span>
				<p><strong>www.airforce-eshop.cz</strong></p>	
			</a>  
		</div>  
		<div class="item-eshop" id="elica">   
			<a href="https://www.italskedigestore.cz/elica" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo ital"></span>
					<span class="item-eshop-text">Autorizovaný eshop Elica</span>  
				</span>  
				<span class="item-eshop-link-content-h">      
					<img src="/images/footer/3310-1312488952.jpg">
				</span>
				<p><strong>www.italskedigestore.cz/elica</strong></p>	
			</a>  
		</div>        
		<div class="item-eshop" id="lord">        
			<a href="https://www.vipelektro.cz" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo vip"></span>   
					<span class="item-eshop-text">Německé spotřebiče LORD</span>
				</span>  
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/586840.jpg">
				</span>
				<p><strong>www.vipelektro.cz</strong></p>	
			</a>  
		</div>        
			<div class="item-eshop" id="laura">        
			<a href="https://www.parnizehleni.cz/laurastar" class="item-eshop-link">   
				<span class="item-eshop-link-content">
					<span class="item-eshop-logo laura"></span>   
					<span class="item-eshop-text">Švýcarské žehlící systémy</span>
				</span>      
				<span class="item-eshop-link-content-h">   
					<img src="/images/footer/laurastar-prod.jpg">
				</span>
				<p><strong>www.parnizehleni.cz/laurastar</strong></p>	      
			</a>    
		</div>         
	</div>
	<div class="clear">&nbsp;</div>  
<?elseif($this->node->nodeId == 7444545413):?>
<div id="overOb">   
	<div class="left">
			<p id="overTitle" class="redHistory fs26"><strong>OVĚŘENÝ OBCHOD</strong></p>
			<p id="overp1">Jsme součástí sítě specializovaných<br /> obchodů specSHOP.cz</p>
	</div>
	<div class="right" id="overR">
			<p id="overp2" class="redHistory fs25" ><strong><?=helper_FrontEnd::price($this->historyBasketCount)?></strong></p>
			<p id="overp3">spokojených zákazníků = <br />záruka <a rel="nofollow" href="/bezpecny-nakup">bezpečného nákupu</a> i pro Vás!</p>
	</div>
</div>
<?endif;?>
<?= $this->html ?>