<?
$_cpMap = array(
	
	'title' => 'Název',
	'name' => 'Jméno',
	'html' => 'Popis',  
	'epay' => 'Zařadit mezi placené exporty',
	'cz_html' => 'HTML obsah - CZ',
	'author' => 'Autor',
	'dateShow' => 'Datum zveřejnění',
	'pathToApp' => 'Cesta k aplikaci',  
	'info' => 'Detailní údaje',
	'function' => 'Funkce',
	'email' => 'E-mail',
	'mobil' => 'Mob. telefon',
	'tel' => 'Telefon',
	'foto' => 'Fotografie',
	'fileDescription' => 'Popis souboru',
	'file' => 'Soubor',
	'disableJPGTransform' => 'Zakázat převod PNG na JPG formát', 
	'selectedFiles' => 'Vybrané soubory:',
	'question' => 'Otátka',
	'answer' => 'Odpověd',
	'pageNodeId' => 'Stránka na webu',
	'url' => 'Webová adresa (URL)',  
	'logo' => 'Logo výrobce',
	'description' => 'Popis',	
	'cz_description' => 'Popis',	
	'googleCode' => 'Kód pro Google Analytics',
	'domainPageTitle' => 'Titulek domény',
	'heurekaId' => 'Heureka číslo pro ověřeno zákazníky',
	'id' => 'id',
	'resNo' => 'Číslo zasedání',
	'onHomePage' => 'Banner na HP',
	'onSection' => 'Banner v sekci',
	'when-how'  => 'Datum / Způsob',
	'res' => 'Soubor usnesení',
	'files' => 'Přílohy', 

	'dphQuote' => 'Sazba DPH',
	
	'aStart' => 'Datum začátku akce',
	'aCapacity' => 'Kapacita akce',
	
	'photos' => 'Fotografie',
	'image' => 'Obrázek', 
	'cover1' => 'Cover',
	'cover2' => 'Cover - na homepage',
	'songs'  => 'Písničky',
	'dateEnd' => 'Datum ukončení', 
	'fullpath' => 'Soubor',
	'photo' => 'Obrázek', 
	'tip' => 'Tip',  
	'verifyCode' => 'Verifikační kód pro WebMaster tools',
	'banners' => 'Banner <small>(764 x 340px)</small>',     
	'banners_bottom' => 'Banner - spodní (275x175px)',
	'vyska' => 'Výška',
	'topCategory'=>'Top kategorie',
	'outcommingEmail' => 'Email pro odchozí poštu z webových formulářů',
	'outcommingEmailName' => 'Jméno pro odchozí poštu z webových formulářů',
	'contactEmail' => 'Email pro doručení z webových formulářů',
	'contactEmailName' => 'Jméno příjemce pro doručení z webových formulářů',
	
	'img_thumb_width' => 'Šířka generovaného náhledu obrázku v administraci',
	'eshopEmail' => 'Emailová adresa pro objednávky z eshopu',
	'eshopEmailName' => 'Jméno mailové adresi pro objednávky z eshopu',
	
	'photogallery_resize_method' => 'Použít zadanou šířku zároveň jako maximální výšku',	
	'photogallery_thumb_width' => 'Šířka generovaného náhledu fotogalerie',
	'photogallery_full_width' => 'Šířka generovaného velkého obrázku fotogalerie',
	
	'user_photo_width' => 'Šířka generované fotografie uživatele',
		
	'overviewPhoto' => 'Přehledová fotografie',
	'photos' => 'Fotografie',
	'price' => 'Cena (kč)',
	'price_bic' => 'Cena - Bičové vedení (kč)', 
	'price_spodni' => 'Cena - Spodní vedení (kč)',
	'details' => 'Přiložené soubory',
    'showin' => 'Zobrazit v',    
    'clients' => 'Měli jsme tu čest',
    'externalLinks' => 'Partnerské odkazy v patičce',
    
	'bannersRight' => 'Pravé bannery <br /> <small>280 x 142px</small>',
	'bannersRightPrivate' => 'Pravé bannery - kadeřníci <br /> <small>280 x 142px</small>',
    
    'uemail' => 'Email', 
    'uphone' => 'Telefon',
    'ufullname' => 'Nabízející', 
    'activated' => 'Aktivováno',
    'eshopUrl' => 'Odkaz na zboží v eshopu',
    'notAvailablePhotos' => 'Varianty, kterým neodpovídá fotka (oddělovač ;)',	
    'ulice' => 'Ulice',
    'mesto' => 'Město',
    'psc' => 'PSČ',
    'stat' => 'Stát', 
    'tel' => 'Telefon',
    'fax' => 'Fax',
    'www' => 'WWW stránnky',
	'note' => 'Poznámka', 
    'lokalita' => 'Region 1', 
	'lokalita2' => 'Region 2',
	'lokalita3' => 'Region 3', 
    'size' => 'Velikost (metry čtvereční piste jako m2)',
    'terasa' => 'Terasa (metry čtvereční piste jako m2)',
    'sklep' => 'Sklep (metry čtvereční piste jako m2)', 
    'parkovani' => 'Parkovani (metry čtvereční piste jako m2)',
    'patro' => 'Patro (x. z y)',
    'lokalita' => 'Lokalita', 
    'price' => 'Cena',  
    'fstate' => 'Stav bytu',
    'showOnHP' => 'Zobrazovat na Homepage',
	'titleImage' => 'Grafický nadpis',
	'previewImage' => 'Obrázek v přehledu <br />  <b>228 x 109 px</b>',
	'obrazky' => 'Obrázky',
	'client' => 'Název klienta- <b>Napište nebo vyberte již zadaný</b>',
	'private' => 'Viditelnost',
	'plimage' => 'Obrázek v přehledu produktů <small>310(max) x 205px</small>',
	'plLogo' => 'Logo řady produktů <small>175(max) x 100(max) px</small>',
	'plbImage' => 'Spodní obrázek řady produktů <small>230 x 300(max) px</small>',
	'objem' => 'Objem', 
	'pImage' =>'Obrázek',  
	'color' => 'Barva řady [např.: 8879b8]',    
	'price2' => 'Cena produktu pro kadeřníky',
	'html_private' => 'Text pouze pro kadeřníky',
	'fArchiv' => 'Archiv časopisů ', 
	'fTech' => 'Technická podpora',
	'fOst' => 'Ostatní dokumenty',
	'portrait' => 'Portrét', 
	'pemail' => 'Email',
	'ptel' => 'Telefon', 
	'pwww' => 'WWW',  
 	'darek' => 'Dárek',   
 	'mapa' => 'URL mapy',
	'madresa'  => 'Adresa',
	'htmlHP' => 'Text na homepage',
    'mtel'=> 'Telefon',   
    'mwww'=> 'WWW', 
    'mmisto'=> 'Název školícího centra', 
	'mstat' => 'Stát',
	'salon' => 'Salón',
	'adresa' => 'Adresa',  
	'cemail' => 'Formulář zasílat na email',
	'cjmeno' => 'Jméno příjemce emailu', 
	'tags' => 'Štítky',
	'asGallery' => 'Styl zobrazení', 
	'price2' => 'Běžná cena <Br /> <small> je-li vyšší</small>',
	'znacka' => 'Značka', 
	'video' => 'Video',  
	'hmotnost' => 'Hmotnost<Br /> <small>v gramech</small>',
	'akce' => 'Pŕíznak', 
	'souvisejici' => 'Doporučujeme dokoupit',  
	'kod' => 'Kód zboží',
	'inTop' => 'Zobrazit v záhlaví webu', 
	'skladem' => 'Skladem', 
	'oldid' => 'Staré ID <Br /> <small>je-li třeba</small>',
	'parent' => 'Kategorie',
	'prodejny' => 'Samostatně prodejný',    
	'parametry' => 'Parametry',    
	'novinka' => 'Novinky',
	'logoTop' => 'Šedé logo <br /> <small>131x43 px </small>',  
	'logoMain' => 'Barevné logo <br /> <small>max. 155x55 px </small>',
	'alternativy' => 'Alternativy',  
	'sold' => 'Prodáno x krát <Br /> <small>je možné měnit aktuální nejprodávanější</small>',
	'ordersEmailName' => 'Jméno osoby v emailu na které chodí objednávky',
	'ordersEmail' => 'Email na který chodí objednávky',
	'dph' => 'Výše dph (%)',
	'action' => 'Akce',
	'heureka' => 'Kategorie na heureka.cz',
	'zbozicz' => 'Kategorie na zbozi.cz',
	'EAN' => 'EAN',  
	'preText' => 'Krátký popis',
	'preTextSK' => 'Krátký popis ve slovenštině',
	'htmlSK' => 'Popis ve slovenštině',
	'parametrySK' => 'Parametry ve slovenštině',
	'pretext' => 'Krátký popis',
	'nazev' => 'Název',
	'popis' => 'Popis',
	'hmotnost_od' => 'Hmotnost od',
	'hmotnost_do' => 'Hmotnost do',
	'zdarma_nad' => 'Zdarma_nad',
	'valid' => 'Povoleno',
	'vyrobnik' => 'Výrobník',
	'darek' => 'Dárek',
	'payments' => 'Vyberte povolené platby:',
	'useEmailOR' => 'Text emailu - objednavka prijata',
	'emailORSubject' => 'Předmět',
	'emailOSSubject' => 'Předmět',
	'emailPRSubject' => 'Předmět',
	'useEmailOS' => 'Text emailu - objednavka odeslana',
	'useEmailPR' => 'Text emailu - platba prijata',
	'deletable' => 'Smazano',
	'paymentFirst' => 'Platba proběhne',
	'showOnHome' => 'Zobrazit na Homepage',
	'bioFresh' => 'Biofresh:',
	'noFrost' => 'Nofrost:',
	'smartFrost'=> 'Smartfrost:',
	'objem' => 'Objem šálku',
	'hmotnost' => 'Hmotnost kávy',
	'hrubost' => 'Hrubost mletí',   
	'teplota' => 'Teplota vod',
	'extrakce' => 'Doba extrakce', 
	'hlucnost' => 'Hlučnost',
	'spotreba' => 'Spotřeba',	
	'vyska' => 'Výška',
	'sirka' => 'Šířka',
	'hloubka' => 'Hloubka',
	'pocKom' => 'Počet kompresorů',
	'pocChlad' => 'Počet chladicích okruhů',
	'obsahMraz' => 'Čístý obsah mrazáku',
	'obsahLed' => 'Čístý obsah lednice',
	'podstavna' => 'Podstavná',
	'vyrobnik' => 'Výrobník ledu',		
		 
		
		

	'rimgs' => 'Obrázky vpravo'
	
); 
  

$mVarianta = new module_Varianta();
for ($i = 1; $i <= $mVarianta->variantCount; $i++) {
	foreach ($mVarianta->variantProperty as $key => $value) {
		$_cpMap['varianta_'.$key.'_'.$i] = $value['cMap'];
	}	
}
