<?
function drawArticle($view, $articleNode,$counter){
	$article = $articleNode->getPublishedContent();
	$url = helper_FrontEnd::getPath($view, $articleNode->path); 	
	$date = Utils::formatDate($article->getPropertyValue('dateShow')); 
	$count = 120;  
	$html = helper_FrontEnd::reduceText(strip_tags($article->getPropertyValue('html')), 375, false, true);	  
	  
	$authorPhoto = helper_FrontEnd::getPhoto('photos', $article, $article->fotoShowName , $article->fotoShowName, 1);     
	$cl = $cds= '';     
						//$clColor = $counter == 2 ? " bcg-pink" : " bcg-grey"; 
						$clColor = " bcg-grey";        
                        if(($counter %4) == 0)   
						$cl = 'art-it-np';  
						if($counter == 2 || $counter == 6)        
						$cl = 'art-it-np-r';   
						if(($counter+1)%4 == 0) 
						{
						$cds = ' ar-l';
						}   
	?>
	<div class="item <?=$cl?><?=$cds?>">   
                        	<div class="<?=$clColor?>">     
                        			<a href="<?=$url?>">
                        				<img data-LL-src="<?=$authorPhoto['path']?>"  alt="<?=$authorPhoto['name']?>"> 
                        				<noscript><img src="<?=$authorPhoto['path']?>"  alt="<?=$authorPhoto['name']?>"/></noscript></a>
                            <div>                 
                                  <h3><a href="<?=$url?>"><?=$articleNode->title;?></a></h3>    
                                <p><?=helper_Frontend::reduceText(strip_tags($article->getPropertyByName('html')->value),60, false, true);?>  
                               	<a class="more" rel="nofollow" href="<?=$url?>">Více informací ></a></p>
                            </div> 
                        </div>  
                        </div> 	     
	<?
	} 
?>      
<?=$this->pageText?>  
<div class="spacer20"></div>    
<div class="articles"> 
	<?$x = 0;
	foreach ($this->articlesNodes as $child):   
		drawArticle($this, $child,$x); 
			$x++;   
	endforeach; 
	?>   
	 <div class="clear"> </div> 
	<?=$this->render('templates/Listing/FloatingWithArrows.phtml'); ?> 
	<div class="spacer20"></div> 
</div> 