   
	    <form enctype="multipart/form-data" method="post" id="mform">
	    <?
		switch ($this->curentAction){
			default: 
			case 'index';?>
				<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabs-1">Emailing - odeslané emaily</a></li> 
				    </ul>
				    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom"> 
					<?=$this->pageContent;?>
				</div>  
								</div>  
			<?break;
			case 'send'; 
				?>
					 <div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabs-1">Emailing - odeslat newsletter</a></li> 
				    </ul>
				    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom"> 
				    	<?=$this->render('/controls/admin/forms/MailingSend.phtml');?>  
								</div>  
								</div>  
				             
				<?
				break; 
			case 'newsletter'; 
				?>
					 <div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabs-1">Newsletter</a></li> 
				    </ul>
				    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom">  

				    <?=$this->pageContent;?>   
								</div>  
								</div>   
				             
				<?
				break; 
				
			case 'sent'; 
				?> 
				 <div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabs-1">Emailing - odeslané emaily</a></li> 
				    </ul>
				    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom"> 
				    	<?=$this->pageContent;?>  
								</div>  
								</div>    
				<?
				break; 
				
			case 'users'; 
				?> 
				<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all"> 
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabs-1">Emailing - správa příjemců</a></li> 
				    </ul>
				    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom"> 
				    	<?=$this->pageContent;?>  
								</div>  
								</div>    
				<?
				break; 
			case 'listemail';?>
			
			<?break;
		}
		 
		?>
		</form>  
		   <script type="text/javascript">
				    $(function() {
				        $( "#tabsright" ).tabs(); 
				    }); 
				    </script> 
				     