<?
	switch ($this->curentAction){
		default:
		case 'index'; 
			?>
				<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="#tabs-1">Soubory na webu</a></li>   
				    </ul>
				    <div id="tabs-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
				    	<div id="sfup">
				    	<?php 
				    	$this->disableJSFUTemplates = true; 
				    	$this->refreshGrid = true;  
				    	?>
				    	<?=$this->render('controls/admin/content/_MuiltiFiles2.phtml');?>       
				    	</div> 
				    	<?=$this->render('/controls/admin/forms/SfHome.phtml');?>
						<?=$this->pagesList;?>       
					</div>   
				</div> 
                <script type="text/javascript"> 
			    $(function() { 
			        $( "#tabsright" ).tabs(); 
			    });
			    </script> 
			<?
			break; 
		case 'detail';
		case 'new'; 
			?>
			<?=$this->pageContent;?>   
			<?
			break; 
	}
	
					