<ul> 
	<li>
		<a href="#" onclick = "refreshTab('advertsHome', '<?=$this->url(array('amodule' => 'companies','action' => 'home'))?>'); return refreshTab('vypisDole', '/cms/pages/list/controler/pages/tree/1/nosortinfo/1/node/33295');">
		Firmy
		</a>
		<ul style="padding-left:15px;">   
			<!-- 
			<li>
				<a href="#" onclick = "refreshTab('advertsHome', '<?=$this->url(array('amodule' => 'ppc','action' => 'home'))?>'); return refreshTab('vypisDole', '<?=$this->url(array('amodule' => 'ppc','action' => 'listPPC'))?>');">
				PPC kampaně 
				</a>
			</li>
			 --> 
			<li>
				<a href="#" onclick = "refreshTab('advertsHome', '<?=$this->url(array('amodule' => 'adresar','action' => 'home'))?>'); return refreshTab('vypisDole', '<?=$this->url(array('amodule' => 'adresar','action' => 'adresarOverview'))?>');">
				Firemní zápisy - adresář firem
				</a> 
			</li>
			<li>
				<a href="#" onclick = "refreshTab('advertsHome', '<?=$this->url(array('amodule' => 'articles','action' => 'home'))?>'); return refreshTab('vypisDole', '<?=$this->url(array('amodule' => 'articles','action' => 'articlesOverview'))?>');">
				Články (PR)
				</a> 
			</li>
			<li>
				<a href="#" onclick = "alert('V rekonstrukci'); return false; refreshTab('advertsHome', '<?=$this->url(array('amodule' => 'ppc','action' => 'home'))?>'); return refreshTab('vypisDole', '<?=$this->url(array('amodule' => 'ppc','action' => 'listPPC'))?>');">
				PPC 
				</a>
			</li>
		</ul> 
	</li>  
</ul>  