	<h1>Reklama - firmy</h1>  
	<!-- 
	<h2>Nejprve vyberte fotogalerii</h2>
	<form id="domainSelectorForm" method="get" action="/cms/advertising/index/subdomain/">  
	<?=$this->formSelect('subdomain', $this->inputGet->subdomain, array(), $this->config->instance->domains) ?>
	<?=$this->formSubmit(  
		'OK',  
		'OK',
		array(
			'onclick' => "window.location.href = dojo.byId('domainSelectorForm').action + dijit.byId('subdomain').getValue(); return false;"  
		)  
	)?> 	   
	</form>
	 -->  