<div class="dijitTabContainer dijitContainer dijitLayoutContainer" style="width:100%; height:450px; overflow:auto;">
<div id="err_PageForm"></div>
<form method="post" id="PageForm" name="PageForm">
<? if($this->input->id):// editace ?>
	<?php echo $this->formHidden('id',$this->input->id) ?>  
<? endif; ?> 

<table class="modalTable">		
	<tr>
		<td class="formcell tkey">Klient</td>
		<td class="formcell"><?=$this->formText('title',$this->input->title, array('class'=>'ftext', 'trim'=>'true', 'required'=>'true')) ?></td>
	</tr>
	<tr>
		<td class="formcell">Email</td>
		<td class="formcell"><?=$this->formText('email',$this->input->email, array('class'=>'ftext', 'trim'=>'true', 'required'=>'true')) ?></td>
	</tr>                
	<tr>
		<td class="formcell">URL webu</td>
		<td class="formcell"><?=$this->formText('url', $this->input->url, array('class'=>'ftext', 'trim'=>'true', 'required'=>'true')) ?></td>
	</tr>
	<tr> 
		<td class="formcell">Cena <a class="helpico" href="#" title="2, 2.50 apod">&nbsp;</a></td>
		<td class="formcell"><?=$this->formText('price', $this->input->price, array('class'=>'ftext', 'trim'=>'true', 'required'=>'true')) ?></td> 
	</tr>
	<tr> 
		<td class="formcell">Datum <b>začátku</b> kampaně</td>
		<td class="formcell"><?=$this->formTextDate('from', $this->input->from , array('required'=>'false', 'invalidMessage' => "Nesprávný formát", 'value'=>'')) ?></td>
	</tr>
	<tr>
		<td class="formcell">Datum <b>konce</b> kampaně</td>
		<td class="formcell"><?=$this->formTextDate('too', $this->input->too , array('required'=>'false', 'invalidMessage' => "Nesprávný formát", 'value'=>'')) ?></td>
	</tr>	
	<tr>
		<td class="formcell">Doména</td>
		<td class="formcell"><?php echo $this->formSelect('domain', $this->input->domain , array('autocomplete'=>'true','value'=>$this->type), $this->domains) ?></td>
	</tr>	
	
</table>
<? if($this->input->id): ?>
<?php echo $this->formSubmit('saveContentB', 'Uložit', array('class'=>'fsubmit', "onclick" => "return submitFormAjax('PageForm', '".$this->url(array('action' => 'savePPC'))."', 'vypisDole', 'modal', '', true );", 'iconClass' => "noteIcon")) ?>		
<? else: ?>
<?php echo $this->formSubmit('saveContentB', 'Uložit', array('class'=>'fsubmit', "onclick" => "return submitFormAjax('PageForm', '".$this->url(array('action' => 'savePPC'))."', 'vypisDole', 'modal', '', true );", 'iconClass' => "noteIcon")) ?>		
<? endif; ?>

</form>
</div>  