<?php echo $this->render('parts/header.phtml'); ?>
	<?php if(!$this->logged): ?>
		<?php echo $this->render('controls/admin/login.phtml'); ?>	
	<?php else: ?>		
	 
	  <div id="sfup">
				    	<?php 
				    	$this->disableJSFUTemplates = true;   
				    	$this->refreshGrid = false;   
						$this->directUploadCallback = $this->request->getParam('callBackInput'); 
				    	$this->fromWysiwg = true;  
				    	$this->multiFileOptions['maxFiles'] = 999; 
				    	?>
				    	<?=$this->render('controls/admin/content/_MuiltiFiles2.phtml');?>       
				    	</div> 
				    	 
	  
	<? endif; ?>	  
<?php echo $this->render('parts/footer.phtml'); ?> 