<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="Author" content="www.bestof.cz" />
		<meta name="Language" content="czech" />
		<meta name="Distribution" content="global" />
		<meta name="Robots" content="INDEX,FOLLOW" />
		<meta name="Expires" content="never" />
		<meta name="Revisit-after" content="7 Days" />

		<meta name="Resource-type" content="document" />
		<!-- <link rel="shortcut icon" href="/images/favicon.ico"> -->
		<title>Náhled</title>
		<link href="/styles/screen2.css" media="screen" rel="stylesheet" />
		<link href="/styles/print.css" media="print" rel="stylesheet" />
		<script type="text/javascript" src="/js/functions.js"></script>	
		<script type="text/javascript">AC_FL_RunContent = 0;</script>
		<script type="text/javascript" src="/js/AC_RunActiveContent.js"></script>
		
	</head>
<body >		
xxxxx
</body>
</html>