<div class="dijitTabContainer dijitContainer dijitLayoutContainer" style="width:100%; height:450px; overflow:auto;">
<div id="err_PageForm"></div>
<form method="post" class="validate" id="PageForm" name="PageForm">	
		<table class="normal">
			<tr>
				<td>Jméno a příjmení <span class="redValid">*</span></td>
				<td><?=$this->formText('name', $this->customer->jmeno.' '.$this->customer->prijmeni, array('class'=>'validate[required,length[0,100]] text-input'))?></td>
			</tr>
			<tr>
				<td>Email <span class="redValid">*</span></td>
				<td><?=$this->formText('email', $this->customer->email, array('class'=>'validate[required,custom[email]] text-input'))?></td>
			</tr>
			<tr>
				<td>Telefon <span class="redValid">*</span></td>
				<td><?=$this->formText('telefon', $this->customer->telefon, array('class'=>'validate[required,custom[onlyNumber]] text-input'))?></td>
			</tr>
			<tr>
				<td>Ulice <span class="redValid">*</span></td>
				<td><?=$this->formText('ulice', $this->customer->ulice, array('class'=>'validate[required,length[0,100]] text-input'))?></td>
			</tr>
			<tr>
				<td>PSČ <span class="redValid">*</span></td>
				<td><?=$this->formText('psc', $this->customer->psc, array('class'=>'validate[required,custom[onlyNumber]] text-input'))?></td>
			</tr>
			<tr>
				<td>Město <span class="redValid">*</span></td>
				<td><?=$this->formText('mesto', $this->customer->mesto, array('class'=>'validate[required,length[0,100]] text-input'))?></td>
			</tr>
			<tr>
				<td>Emailing </td>
				<td><input type="checkbox" name="mailing" value="1" <?=$this->customer->mailing?'checked':''?>></td></td>
			</tr>
		</table>   
		<!-- <table class="ftable">
			<tr>
				<td class="fkey">Jméno a příjmení</td>
				<td class="fval"><?=($this->customer->jmeno)?> <?=($this->customer->prijmeni)?></td>
				<td class="fkey">Email: </td>
				<td class="fval"><?=($this->customer->email)?></td>
			</tr>  
			<tr>
				<td class="fkey">Ulice: </td>
				<td class="fval"><?=($this->customer->ulice)?></td>
				<td class="fkey">Telefon:</td> 
				<td class="fval"><?=$this->customer->telefon?></td>
			</tr> 
			<tr>
				<td class="fkey">PSČ: </td>
				<td class="fval"><?=($this->customer->psc)?></td>
				<td class="fkey">Město:</td> 
				<td class="fval"><?=$this->customer->mesto?></td>
			</tr>     
		</table>  -->
	<?php //  $this->formSubmit('saveContentB', 'Uložit', array('class'=>'fsubmit', "onclick" => "return submitFormAjax('PageForm', '".$this->url(array('action' => 'saveOrder'))."', 'vypisDole', 'tab-refresh', '', true );", 'iconClass' => "noteIcon")) ?>
	<div class="spacer10"></div>	 
	    <input type="submit"  name="back" id="saveSetB" value="Uložit" class="fsubmit fsBig">
	    <a onclick="window.history.back(); return false;" id="cancelLink" title="Změny nebudou uloženy">Zrušit</a>
</form>
</div>  