    <?
	switch ($this->curentAction){
		default:
		case 'index';
			?>
				
				<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Váš eshop</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->render('controls/admin/modules/Eshop/Home.phtml')?>  
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			<?
			break;
		case 'listItems';
			?> 
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Eshop - výpis produktů</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->pagesList;?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break; 
		case 'conversion';
			?> 
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Eshop - nastavení konverzí</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->conversion;?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break; 
		case 'addItem';
			?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Eshop - nový produkt</a></li> 
				    </ul>
				    <div id="tabs-1"> 
				    	<?=$this->pageContent;?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			  
			<?
			break; 
		case 'editproduct';
			?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Eshop - editace produktu</a></li> 
				    </ul>
				    <div id="tabs-1">  
				    	<?=$this->pageContent;?>     
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break;
		
			case 'settings';
			?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Nastavení e-shopu</a></li> 
				    </ul>
				    <div id="tabs-1">  
				    	<?=$this->settings;?>       
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break;
			case 'listdelivery';?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Možnosti dopravy</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->pagesList;?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break; 
		case 'delivery';?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Vložit dopravu</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->basicForm;?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break;
		case 'payment';?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Vložit platbu</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->basicForm;?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break;
		case 'listpayments';?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Platby</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->pagesList;?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break;
			
			case 'listorders';?>
			<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
				    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
				        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Objednávky</a></li> 
				    </ul>
				    <div id="tabs-1">
				    	<?=$this->ordersList?>    
					</div> 
				</div>
                <script type="text/javascript">
			    $(function() {
			        $( "#tabsright" ).tabs(); 
			    });  
			    </script> 
			
			<?
			break;
			
			case 'listreviews';?>
						<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
							    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
							        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Hodnocení e-shopu</a></li> 
							    </ul>
							    <div id="tabs-1">
							    	<?=$this->pagesList?>    
								</div> 
							</div>
			                <script type="text/javascript">
						    $(function() {
						        $( "#tabsright" ).tabs(); 
						    });  
						    </script> 
						
						<?
						break;
			case 'addnewreview';?>
												<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
													    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
													        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Přidat nové hodnocení eshopu</a></li> 
													    </ul>
													    <div id="tabs-1">
													    	<?=$this->basicForm;?>     
														</div> 
													</div>
									                <script type="text/javascript">
												    $(function() {
												        $( "#tabsright" ).tabs(); 
												    });  
												    </script> 
												
												<?
												break;
				case 'listcustomers';?>
												<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
													    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
													        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Zákazníci</a></li> 
													    </ul>
													    <div id="tabs-1">
													    	<?=$this->pagesList?>    
														</div> 
													</div>
									                <script type="text/javascript">
												    $(function() {
												        $( "#tabsright" ).tabs(); 
												    });  
												    </script> 
												
												<?
												break;

			case 'listvouchers';?>
						<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
							   <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
							       <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Dárkové poukazy</a></li> 
							    </ul>
							    <div id="tabs-1">
							    	<?=$this->pagesList?>    
								</div> 
						</div>
						<script type="text/javascript">
						$(function() {
						     $( "#tabsright" ).tabs(); 
						  });  
						</script> 
			<?
			break;
			case 'stats';?>
									<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
										   <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
										       <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Prodávanost produktů</a></li> 
										    </ul>
										    <div id="tabs-1">
										    	<?=$this->pagesList?>    
											</div> 
									</div>
									<script type="text/javascript">
									$(function() {
									     $( "#tabsright" ).tabs(); 
									  });  
									</script> 
						<?
						break;
			case 'edituser';?>
				<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
							    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
							        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Uživatel</a></li> 
							    </ul>
							    <div id="tabs-1">
							    	<?=$this->basicForm?>    
								</div> 
							</div>
			                <script type="text/javascript">
						    $(function() {
						        $( "#tabsright" ).tabs(); 
						    });  
						    </script> 
						
			<?break;
			case 'editorder';?>
							<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
										    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
										        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Objednávka</a></li> 
										    </ul>
										    <div id="tabs-1">
										    	<?=$this->basicForm?>    
											</div> 
										</div>
						                <script type="text/javascript">
									    $(function() {
									        $( "#tabsright" ).tabs(); 
									    });  
									    </script> 
									
						<?break;
			case 'vouchersgen';?>
					<div id="tabsright" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
							    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
							        <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab"><a href="#tabs-1" class="ui-tabs-anchor">Generování poukazu</a></li> 
								</ul>
								<div id="tabs-1">
									    	<?=$this->basicForm?>    
								</div>  
					</div>
						                <script type="text/javascript">
									    $(function() {
								        $( "#tabsright" ).tabs(); 
									    });  
									    </script> 
															
			<?break;
			
			
	}
	
	
	
