	<h1>Objednávky</h1>  
	<!-- 
	<table id="colors"> 
		<tr class="recieved"><td>Přijatá platba, neodesláno (balík)</td></tr>  
		<tr class="sentDobirka"><td>Odesláno dobírkou, čeká se na platbu (dobírka)</td></tr> 
		<tr class="waiting1"><td>Čeká se na platbu - urgence 1. (balík)</td></tr> 
		<tr class="waiting2"><td>Čeká se na platbu - urgence 2. (balík)</td></tr>  
		<tr class="sent"><td>Odeslaná a zaplacená objednávka (balík, dobírka)</td></tr>   
		<tr class="storno"><td>Stornovaná objednávka</td></tr>   
	</table>  
	 -->     