<div class="dijitTabContainer dijitContainer dijitLayoutContainer" style="width:100%; height:450px; overflow:auto;">
<div id="err_PageForm"></div>
<form method="post" id="PageForm" name="PageForm">
	<div id="order">	
		<h2>Příplatek</h2>
		<table>   
			<tr> 
				<td>Název </td>
				<td><input name="nazev" type="text" value="<?=$this->priplatek['nazev']?>"></td>
			</tr>
			<tr> 
				<td>Cena: </td>
				<td><input name="cena" type="text" value="<?=$this->priplatek['cena']?>"></td>
			</tr>


					

		</table>
			<br/>
		
		<?=$this->formSubmit('saveContentB', 'Uložit', array('class'=>'fsubmit', "onclick" => "return submitFormAjax('PageForm', '".$this->url(array('action' => 'savePriplatek'))."', 'vypisDole', 'tab-refresh', '', true );", 'iconClass' => "noteIcon")) ?>
		<?=$this->formHidden('id',$this->priplatek['id']);?> 
		  
		 
		
		 
	</div> 
</form>
</div>  