<form method="post" id="PageForm" name="PageForm">
	<table class="normal">	
		<tr>
			<td class="formcell tkey tkey_form">Jméno</td>
			<td class="formcell"><?=$this->formText('name', array(), array('style' => 'width:350px; height:90px;'));?></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Pro</td>
			<td class="formcell"><?=$this->formTextarea('pros', array(), array('style' => 'width:350px; height:90px;'));?></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Proti</td>
			<td class="formcell"><?=$this->formTextarea('cons', array(), array('style' => 'width:350px; height:90px;'));?></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Celkové</td>
			<td class="formcell"><?=$this->formTextarea('summary', array(), array('style' => 'width:350px; height:90px;'));?></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Datum hodnocení</td>
			
			<td class="formcell"><?=$this->formTextDate('date',date("Y-m-d"),array())?></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Doba doručení</td>
			<td class="formcell"><input type="number"  name="delivery" min="1" max="5"></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Doprava</td>
			<td class="formcell"><input type="number"  name="transport" min="1" max="5"></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Přehlednost webu</td>
			<td class="formcell"><input type="number"  name="webUsa" min="1" max="5"></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Komunikace</td>
				<td class="formcell"><input type="number"  name="communication" min="1" max="5"></td>
		</tr>
		<tr>
			<td class="formcell tkey tkey_form">Celkové</td> 
				<td class="formcell"><input type="number"  name="total_rating" min="1" max="5"></td>
		</tr>
	</table>
	<div class="spacer10"></div>
	<?=$this->formSubmit('save', 'Uložit', array('class'=>'fsubmit fsBig', "onclick" => "return submitFormAjax('PageForm', '".$this->url(array('action' => 'addnewreview'))."', 'vypisDole', 'tab-refresh', '', true );", 'iconClass' => "noteIcon")) ?>
	<a onclick="window.history.back(); return false;" id="cancelLink" title="Změny nebudou uloženy">Zrušit</a>
</form>