<?
$i = $this->kident;
?>
<div id="kategorieBody_<?=$i?>" class="bodyCat" <?=$display;?>>
	<strong><span class="f15">Kategorie <?=$i?></span></strong>
	<div class="spacer10"></div>
	<table>	
	<tr>
			<td>Název:</td>
			<td><?=$this->formText('category_' . $i, $this->kategorie[$i - 1]['title'])?></td>
			<?// Přiřadit: <?=$this->formSelect('kSelect_' . $i, $this->kategorie[$i -1]['multiOption'], '', array( 0 => 'jednu vlastnost', 1 => 'více vlastností'))= Utils::getHelpIco('Každému produktu bude možno přidělit:'); ?>
			<td>Smazat kategorii: <?=$this->formCheckbox('kDelete_' . $i)?>
			<?=$this->formHidden('kId_'. $i, $this->kategorie[$i - 1]['id'])?><?= Utils::getHelpIco('Zašktnutím a uložením smažete kategorii'); ?></td>
			<td><a <?=$display;?> href="#"  id="nb"   prop="<?=$i?>" class="nice catText" role="button" aria-disabled="false"><span class="ui-icon ui-icon-carat-2-n-s"></span><span class="ui-button-text">Další možnosti</span></a></td>
		</tr>
		</table>
		
		<div class="spacer10"></div>
		<div id="catSeo_<?=$i?>" style="display:none;">
			<?=$this->formWysiwyg('kategorie_' . $i, $this->kategorie[$i - 1]['text'], array(), array(),array('width' => '300px'))?>
			<table>
				<tr>
					<td>Obrázek</td>
					<td><?=$this->formFileSelect('kPhotos_' . $i, $this->kategorie[$i -1]['photos'],array(),array(), array('showSelectFile' => true,  'showUploadFile' => true, 'uploadFileDirectoryNodeId' => 7329 ))?></td>
				</tr>
			</table>
		</div>
		<table id="kv_<?=$i?>" class="magL30">
		<tr>
			<td colspan="3"><span class="f14">Vlastnosti kategorie <?=$i?>:</span><td>
		</tr>
		<?for($j=1; $j<=150; $j++): 
			if($this->kategorie[$i - 1]['options'][$j-1]['title'] || $j < 3){

			} else {
				break; 
			} 
			$this->kident = $i;  			
			$this->vident = $j;   
			echo $this->render('controls/admin/modules/Eshop/Settings_kategorie_item_vlastnost.phtml');  
			?>
		<?endfor;?>
		</table>
		<script type="text/javascript" charset="utf-8">
		var nextVlastnost<?=$i?> = <?=($j-1)?>;
		</script>	   
		
		<div class="spacer10"></div>  
		<a href="#" onclick="nextVlastnost<?=$i?>++; loadKatVlastnost(<?=$i?>, nextVlastnost<?=$i?>);return false;" id="nb" class="nice addOtion" role="button" aria-disabled="false"><span class="ui-icon ui-icon-circle-plus"></span><span class="ui-button-text">Přidat vlastnost</span></a>
		<div class="spacer10"></div>
</div> 