<div id="footer" class="posAbsolute">   	
	<div id="footerInner">
		<div class="fLeft marTop4">
			<a href="/"><img src="/images/logoF.png" alt="Logo - LIEBHERR"/></a>
		</div>
		<div class="fLeft marLeft20 fFaceArial fs12">
			<ul>
				<li class="fLeft"><a href="#">Porovnání produktů</a></li>
			</ul>
		</div>
		<div class="fRight white fs13 i-table marRight5">
			<span id="telIcoF" class="i-block marBottom4 vAlingMid"></span>
			<span class="i-block fs16 marRight20">HOTLINE</span>8–18 hod.: <span class="fs17">+420 <strong>777 56 93 86</strong></span>
		</div>
	</div>	
</div> 