					 <div id="promo">
						<script language="javascript">
                            if (AC_FL_RunContent == 0) {
                                alert("This page requires AC_RunActiveContent.js.");
                            } else {
                                AC_FL_RunContent(
                                    'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0',
                                    'width', '920',
                                    'height', '169',
                                    'src', '/flash/promo-banner',
                                    'quality', 'high',
                                    'pluginspage', 'http://www.macromedia.com/go/getflashplayer',
                                    
									
									'align', 'middle',
                                    'play', 'true',
                                    'loop', 'true',
                                    'scale', 'showall',
                                    'wmode', 'transparent',
                                    'devicefont', 'false',
                                    'id', 'promo-banner',
                                    'bgcolor', '#ffffff',
                                    'name', 'promo-banner',
                                    'menu', 'false',
                                    'allowFullScreen', 'false',
                                    'allowScriptAccess','sameDomain',
									
									
                                    'movie', '/flash/promo-banner',
                                    'salign', ''
                                    ); //end AC code
                            }
                        </script>
                        <noscript>
                        	<p>Pro zobrazení je nutný mít povolený javascript.</p>
                        </noscript>
                    </div>