<?
$this->txtPage = true;  
$state = false;
if(isset($this->input->register)){  
	list($state, $messages) = $this->mCustomers->sendLoginInfo($this->input);
	Helpers::addMessage($state, $messages, $this);
}
?>
<?php if(count($this->messages)): ?>
	<?= $this->render('parts/messages.phtml'); ?>				
<?php endif; ?>

<?php if(!$state): ?>		
	<p>Zadejte Váš email, přihlašovací údaje Vám znovu zašleme.</p>	
	<div class="spacer10"> </Div>
	<div class="form">
	<form action="<?=$_SERVER['REDIRECT_URL']?>" method="POST">
	<?= $this->pageText ?>
	<table>
		<tr>  
			<td>Váš e-mail</td>			 
			<td><?=$this->formText('email', $this->input->email, array('class' => 'nice s150'))?> <span class="cred">*</span></td>		
		</tr>  
		<tr>
			<td colspan="2">
			<button type="submit" name="register" id="sendBtn"> 
		</button> 
			</td>
		</tr> 
	</table>
	</form>
	</div>
<? else: ?>
	<!--<p>Děkujeme za Vaší registraci.</p>-->
<? endif; ?>