	<div class="mDiv">
			<div class="ftitle">Filtr:</div> 
		</div> 
		<div class="tDiv"> 	
			filtr: <?=$this->formSelect('status',$this->input->status,array("onchange"=> "$('#".$this->tableId."').flexReload()"), $this->status)?>
		    <?=$this->formSelect('type',$this->input->type, array("onchange"=> "$('#".$this->tableId."').flexReload()"), $this->type)?>
		    Hledat: <input id="fmFilterSel" name="search" type="text" />  
		    <input type="button" onclick="$('#<?=$this->tableId?>').flexReload()" name="saveSetB" id="saveSetB" value="Filtrovat" class="fsubmit">
		   
 		</div>   