	<? 

	$atribs = $this->wAtribs; 
	?>
	<textarea id="<?=$atribs['idecko']?>" name="<?=$atribs['name']?>" rows="15" cols="80"><?=htmlspecialchars($atribs['value'])?></textarea>
	<script type="text/javascript"> 
	//tinymce.execCommand('mceRemoveControl',false,<?=$atribs['idecko']?>);
	//tinyMCE.execCommand("mceAddControl", true, <?=$atribs['idecko']?>);
	try
	{  
			
tinymce.init({
    content_css : "/styles/general.css",
    document_base_url : '/',    
    theme: "modern",
    language_url : '/admin/js/tiny_mce/langs/cs.js',
    language : 'cs',
	relative_urls: false,
	remove_script_host: true, 
	browser_spellcheck : true,  
	language : 'cs',   
	entity_encoding: "raw", 
	mode: "exact",     
	elements : "<?=$atribs['idecko']?>",   
	theme_advanced_toolbar_location : "top", 
	theme_advanced_resizing : true,   
   plugins: [  
                "advlist link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "table contextmenu directionality emoticons template textcolor paste textcolor colorpicker textpattern"
        ],

        toolbar1: "newdocument fullpage | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | formatselect fontsizeselect",
        toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | insertdatetime preview | forecolor backcolor",
        toolbar3: "table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker | visualchars visualblocks nonbreaking restoredraft",

        menubar: false,
        toolbar_items_size: 'small',

        style_formats: [
                {title: 'Bold text', inline: 'b'},
                {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                {title: 'Example 1', inline: 'span', classes: 'example1'},
                {title: 'Example 2', inline: 'span', classes: 'example2'},
                {title: 'Table styles'},
                {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],

   file_browser_callback : cmsFileBrowser,
    height:"<?=$atribs['height']?>", 
	width:"<?=$atribs['width']?>" 
});
}
	catch(err)
	{
  		//alert(err); 
	}   
 <?
	
	 //   $this->tinyLoaded = true;
		 
	 if(!$this->tinyLoaded):?>	
		function cmsFileBrowser (field_name, url, type, win) {
		  	
		   //alert("Field_Name: " + field_name + "nURL: " + url + "nType: " + type + "nWin: " + win); // debug/testing

		    /* If you work with sessions in PHP and your client doesn't accept cookies you might need to carry
		       the session name and session ID in the request string (can look like this: "?PHPSESSID=88p0n70s9dsknra96qhuk6etm5").
		       These lines of code extract the necessary parameters and add them back to the filebrowser URL again. */
		    //  alert(type);alert(type == 'file');
		   	if(type == 'image'){ 
		   		cmsURL = '/cms/sf/index/isPopup/1/nowysiwyg/1/noresize/1/callBackInput/src' + field_name; 
		   	} else {
		   		cmsURL = '/cms/pages/index/isPopup/1/nowysiwyg/1/callBackInput/' + field_name; // isPageSelectPopup/1/
		   		cmsURL = '/cms/sf/index/isPopup/1/nowysiwyg/1/callBackInput/' + field_name;    
		   	} 
 
		    tinyMCE.activeEditor.windowManager.open({
		        file : cmsURL, 
		        title : 'Nahrajte soubor', 
		        width : 400,  // Your dimensions may differ - toy around with them!
		        height : 200, 
		        resizable : "no", 
		        inline : "yes",  // This parameter only has an effect if you use the inlinepopups plugin!
		        close_previous : "no"
		    }, {
   			 setUrl: function (url) {
    		  win.document.getElementById(field_name).value = url;
    		}
 		 });
 		 return false;
		}
	<? endif; ?>  
	</script> 
	<?php 
	$this->tinyLoaded = true;
	?>
	 