<script src="/js/prototype.js" type="text/javascript"></script>
<script src="/js/scriptaculous.js?load=effects,builder" type="text/javascript"></script>
<script src="/js/lightbox.js" type="text/javascript"></script>
<?
$i = 0;
foreach ($this->photos as $path => $name){
	if(!$path){ continue; }
	
	if($this->showSpacer){
		if($i%$this->photosPerLine == 0){
			?>
			<div class="spacer10">&nbsp;</div>
			<?
		}
	}
    list($nodeId, $n) = content_SFSFile::parseSFSPath($path);
    $this->photoPath = $this->config->sfFolder . '/' . $nodeId . '/' . $this->thumbName . '-' . content_SFSFile::getFileExtension($n) . '/' . $n;
    $this->photoPathFull = $this->config->sfFolder . '/' . $nodeId . '/' . $this->fullName . '-' . content_SFSFile::getFileExtension($n) . '/' . $n;
    $this->photoTitle = $name;
	
    echo $this->render($this->galleryItemTemplate);
    
	$i++;
}
?>