<!--
<div style="float:right; width:170px; height:80px;">
	<div class="box enquiry">
		<div class="enquiry_top"></div>
		<div class="enquiry_body">
			<strong>Líbí se Vám nový intranet?</strong>
			<table id="tbl" style="">
				<tr><td class="bar"><div class="voted bgGreen" style="width: 80%;">&nbsp;</div></td><td><a href="#">ano</a></td></tr>
				<tr><td class="bar"><div class="voted bgRed" style="width:20%"></div></td><td><a href="#">ne</a></td></tr>
			</table>
		</div>
		<div class="enquiry_bottom"></div>
	</div>
</div>
http://nova.rada-severovychod.cz/cms/intranet/welcome/controler/intranet?e=13&vote=45
-->


<?=$this->pageText?>
<h2>Naposledy přidané soubory</h2>

<table id="dashboard">
		<tr>
			<td style="width:100%;">
				<div class="dPanel">
					<div class="dHead">
						<span class="ico2 dIntranet">&nbsp;</span> <b>Intranet - naposledy přidané dokumenty</b>
					</div>
					<div class="dBody">
					<table>
						<?php foreach ($this->files as $node): 
						$url = Utils::getAdminUrl($node, $this);
						?>
						<tr class="<?=$this->tableTrCycle('licha','suda')?>">
							<td>&nbsp;<?=Utils::getStateIcon($node);?>&nbsp;<a href="<?=$url?>"><?=$node->title?></a></td>
							<td><?=$this->systemUsers[$node->owner]?></td>
							<td><?=Utils::formatTime($node->dateCreate)?></td>
						</tr>						
						<? endforeach;  ?>
					</table>
					</div>
					<div class="dFoot">
						<div class="dbBL">&nbsp;</div>
						<div class="dbBR">&nbsp;</div>
					</div>
					<div class="dbTL">&nbsp;</div>
					<div class="dbTR">&nbsp;</div>
				</div>
			</td>
		</tr>			
	</table> 
	<!--
<ul>
<? 
	for ($i = 0; $i <= 10; $i++) :
		$file = $this->files[$i];
		if(!$file){
			break;
		}
?>	
		<li>
			<img src="<?=$file->ico?>" alt="" /> <b><?=$file->title?></b> <?=Utils::getFrontEndLink($file->path)?> <br/>
			<? if($file->description): ?>
			<?=$file->description?>
			<? endif; ?>
		</li>
	
<? endfor; ?>
</ul>
-->